"""
symptom_vocab.py — authoritative symptom key vocabulary for the Jeevanya rule engine.

Generated from rules_engine.py — every key here maps to at least one rule condition.
The /extract-symptoms LLM prompt uses this list as its exclusive output vocabulary.

Human-readable labels for the confirm-back screen are provided in SYMPTOM_LABELS
for each supported language (en, hi, mr, ta).

NOTE on `stiff_neck`, `mild_cough`, `runny_nose`, `cough`:
These are simple English words that also happen to be exact symptom keys — the LLM
will naturally produce them without needing translations in the label map. They're
included in SYMPTOM_KEYS but only minimally labelled.
"""

SYMPTOM_KEYS: list[str] = [
    "abdominal_distension_or_swelling",
    "abdominal_pain_or_loose_motions_gt_3_episodes",
    "abnormal_bleeding_per_vagina",
    "abnormal_chest_wall_movement_on_breathing",
    "active_seizure",
    "altered_sensorium",
    "baby_lying_sideways_malpresentation",
    "bleeding_fresh_blood",
    "bleeding_from_vagina_any_amount",
    "bleeding_pad_soaked_lt_5_min",
    "blurred_vision",
    "breathlessness",
    "breathlessness_at_rest",
    "burn_percent_bsa_gt_20",
    "burn_present",
    "burn_special_area_hands_face_perineum_or_airway",
    "chest_indrawing",
    "chest_pain",
    "chills_and_rigors",
    "contact_with_known_tb_patient",
    "continuous_severe_abdominal_pain",
    "convulsions",
    "convulsions_or_fits",
    "convulsions_or_loss_of_consciousness",
    "cough",
    "cough_more_than_2_weeks",
    "dark_or_cola_coloured_urine",
    "decreased_or_absent_foetal_movements",
    "diarrhea",
    "difficult_breathing",
    "drug_overdose_or_poisoning_with_stable_vitals",
    "ear_pain",
    "ear_problem_reported",
    "excessive_vomiting_unable_to_take_orally",
    "fast_or_difficult_breathing",
    "fever",
    "fever_in_chemo_or_hiv_or_diabetic_patient",
    "fever_more_than_2_weeks",
    "fever_under_101f",
    "fever_with_chills",
    "fever_with_headache_or_chest_pain_or_jaundice",
    "fits",
    "foul_smelling_discharge",
    "fracture_of_hand_or_feet",
    "fracture_with_exposed_bone",
    "fresh_scratches_or_wounds",
    "haemoglobin_7_to_11_despite_30_days_ifa",
    "haemoglobin_lt_7",
    "hanging_or_near_drowning_or_electrocution_or_heat_stroke",
    "headache_or_dizziness",
    "high_bp_gt_140_90_with_or_without_proteinuria",
    "high_fever_with_or_without_abdominal_pain_too_weak_to_get_out_of_bed",
    "high_grade_fever_with_altered_mental_status",
    "history_of_fainting_or_syncope",
    "injury",
    "isolated_long_bone_fracture",
    "lethargic_or_unconscious",
    "limb_injury_with_absent_distal_pulse",
    "liquor_colour_green_or_brown",
    "loss_of_foetal_movement_or_severe_abdominal_pain",
    "low_risk_cough_or_cold",
    "malaria_test_negative",
    "malaria_test_positive",
    "malpresentation",
    "mild_cough",
    "minor_head_injury",
    "minor_symptoms_of_existing_illness",
    "more_than_5_pads_per_day_or_1_thick_cloth_per_day",
    "movement_only_when_stimulated_or_none",
    "multiple_injuries",
    "multiple_pregnancy",
    "noisy_breathing_or_stridor",
    "not_able_to_drink_or_drinking_poorly",
    "not_able_to_drink_or_feed",
    "ongoing_bleeding_vomitus_cough_urine_or_nose",
    "painful_bleeding_per_rectum",
    "painful_swelling_or_wound",
    "pallor",
    "pallor_or_known_anaemia_needing_transfusion",
    "pallor_or_pale_skin_or_conjunctiva",
    "pallor_with_breathlessness_or_foot_swelling",
    "persistent_or_severe_abdominal_pain_or_tenderness",
    "persistent_vomiting",
    "post_seizure_stage",
    "premature_rupture_of_membranes_before_37_weeks",
    "prolonged_labour_pushing_gt_12h_or_gt_8h_multipara",
    "pus_draining_14_days_or_more",
    "pus_draining_less_than_14_days",
    "reduced_urinary_output_with_high_bp",
    "restlessness_or_sudden_behavioral_change",
    "retained_placenta",
    "ruptured_membranes_more_than_18h",
    "runny_nose",
    "severe_headache",
    "severe_headache_with_blurred_vision_or_spots",
    "significant_weight_loss",
    "simple_skin_rash",
    "skin_pinch_goes_back_very_slowly",
    "snake_or_scorpion_bite",
    "stab_or_penetrating_injury",
    "stiff_neck",
    "stroke_fast_signs",
    "subcutaneous_crackles_or_seatbelt_mark",
    "sunken_eyes",
    "suspected_neck_injury",
    "suspected_poisoning_with_unstable_vitals",
    "suspected_sexual_assault",
    "suspected_spine_injury",
    "swelling_face_or_hands",
    "swollen_face_or_hands",
    "swollen_face_or_hands_pitting_oedema",
    "tender_swelling_behind_ear",
    "two_or_more_long_bone_fractures",
    "unable_to_pass_stool",
    "unable_to_pass_urine",
    "vomiting",
    "vomits_everything",
    "water_broke_no_labour_within_24h",
]

SYMPTOM_KEY_SET: set[str] = set(SYMPTOM_KEYS)

# ---------------------------------------------------------------------------
# Human-readable labels for the confirm-back screen.
# Every key must have a label in all 4 supported languages.
# ---------------------------------------------------------------------------
SYMPTOM_LABELS: dict[str, dict[str, str]] = {
    "abdominal_pain_or_loose_motions_gt_3_episodes": {
        "en": "Stomach pain or loose motions (3+ times)",
        "hi": "पेट दर्द या दस्त (3 या अधिक बार)",
        "mr": "पोटदुखी किंवा जुलाब (3 किंवा अधिक वेळा)",
        "ta": "வயிற்று வலி அல்லது மலத்திரவம் (3+ முறை)",
    },
    "abnormal_bleeding_per_vagina": {
        "en": "Abnormal vaginal bleeding",
        "hi": "असामान्य योनि से रक्तस्राव",
        "mr": "असामान्य योनीतून रक्तस्राव",
        "ta": "அசாதாரண யோனி இரத்தப்போக்கு",
    },
    "abnormal_chest_wall_movement_on_breathing": {
        "en": "Abnormal chest movement while breathing",
        "hi": "सांस लेते समय छाती की असामान्य हलचल",
        "mr": "श्वास घेताना छातीची असामान्य हालचाल",
        "ta": "சுவாசிக்கும்போது அசாதாரண மார்பு அசைவு",
    },
    "active_seizure": {
        "en": "Active seizure / fit right now",
        "hi": "अभी दौरा पड़ रहा है",
        "mr": "सध्या झटका येत आहे",
        "ta": "இப்போது வலிப்பு வருகிறது",
    },
    "altered_sensorium": {
        "en": "Confused, disoriented, or unconscious",
        "hi": "भ्रमित, दिशाहीन, या बेहोश",
        "mr": "गोंधळलेले, दिशाहीन, किंवा बेशुद्ध",
        "ta": "குழப்பம், திசைதெரியாமை, அல்லது நினைவிழப்பு",
    },
    "baby_lying_sideways_malpresentation": {
        "en": "Baby lying sideways (malpresentation)",
        "hi": "बच्चा तिरछा है (गलत स्थिति)",
        "mr": "बाळ आडवे आहे (चुकीची स्थिती)",
        "ta": "குழந்தை பக்கவாட்டில் உள்ளது (தவறான நிலை)",
    },
    "bleeding_fresh_blood": {
        "en": "Fresh blood bleeding",
        "hi": "ताजा खून बह रहा है",
        "mr": "ताजे रक्त वाहत आहे",
        "ta": "புதிய இரத்தம் வடிகிறது",
    },
    "bleeding_from_vagina_any_amount": {
        "en": "Vaginal bleeding (any amount during pregnancy)",
        "hi": "योनि से रक्तस्राव (गर्भावस्था में कोई भी मात्रा)",
        "mr": "योनीतून रक्तस्राव (गर्भावस्थेत कोणत्याही प्रमाणात)",
        "ta": "யோனி இரத்தப்போக்கு (கர்ப்பகாலத்தில் எந்த அளவும்)",
    },
    "bleeding_pad_soaked_lt_5_min": {
        "en": "Pad soaked in less than 5 minutes",
        "hi": "5 मिनट से कम में पैड भीग गया",
        "mr": "5 मिनिटांपेक्षा कमी वेळात पॅड भिजला",
        "ta": "5 நிமிடத்திற்கும் குறைவாக பேட் நனைந்தது",
    },
    "blurred_vision": {
        "en": "Blurred or dim vision",
        "hi": "धुंधली दृष्टि",
        "mr": "दृष्टी अंधुक होणे",
        "ta": "மங்கலான பார்வை",
    },
    "breathlessness": {
        "en": "Breathlessness / difficulty breathing",
        "hi": "सांस फूलना / सांस लेने में तकलीफ",
        "mr": "श्वास लागणे / श्वास घेण्यास त्रास",
        "ta": "மூச்சுத் திணறல்",
    },
    "breathlessness_at_rest": {
        "en": "Breathlessness at rest (even without activity)",
        "hi": "आराम के समय भी सांस फूलना",
        "mr": "विश्रांती घेतानाही श्वास लागणे",
        "ta": "ஓய்வில் இருந்தாலும் மூச்சுத் திணறல்",
    },
    "burn_percent_bsa_gt_20": {
        "en": "Burn covering more than 20% of body",
        "hi": "शरीर के 20% से अधिक जलन",
        "mr": "शरीराच्या 20% पेक्षा जास्त जळणे",
        "ta": "உடலின் 20%-க்கும் அதிகமான பகுதி தீயில் சுட்டது",
    },
    "burn_present": {
        "en": "Burn present",
        "hi": "जलन / आग से चोट",
        "mr": "जळणे / आगीने इजा",
        "ta": "தீக்காயம் உள்ளது",
    },
    "burn_special_area_hands_face_perineum_or_airway": {
        "en": "Burn on face, hands, genitals, or airway",
        "hi": "चेहरे, हाथ, गुप्तांग, या सांस की नली पर जलन",
        "mr": "चेहरा, हात, गुप्तांग, किंवा श्वासमार्गावर जळणे",
        "ta": "முகம், கைகள், இனப்பெருக்க உறுப்பு, அல்லது சுவாசப் பாதையில் தீக்காயம்",
    },
    "chest_indrawing": {
        "en": "Chest drawing in when breathing (chest indrawing)",
        "hi": "सांस लेते समय छाती अंदर धंसना",
        "mr": "श्वास घेताना छाती आत ओढली जाणे",
        "ta": "சுவாசிக்கும்போது மார்பு உள்ளே இழுக்கிறது",
    },
    "chest_pain": {
        "en": "Chest pain",
        "hi": "सीने में दर्द",
        "mr": "छातीत दुखणे",
        "ta": "மார்பு வலி",
    },
    "continuous_severe_abdominal_pain": {
        "en": "Continuous severe stomach / abdominal pain",
        "hi": "लगातार तेज पेट दर्द",
        "mr": "सतत तीव्र पोटदुखी",
        "ta": "தொடர்ச்சியான கடுமையான வயிற்று வலி",
    },
    "convulsions": {
        "en": "Convulsions / fits",
        "hi": "दौरे / मिर्गी",
        "mr": "आकडी / झटके",
        "ta": "வலிப்பு / வலிப்பு நோய்",
    },
    "convulsions_or_fits": {
        "en": "Convulsions or fits",
        "hi": "दौरे या झटके",
        "mr": "आकडी किंवा झटके",
        "ta": "வலிப்பு அல்லது வலிப்பு",
    },
    "convulsions_or_loss_of_consciousness": {
        "en": "Convulsions or loss of consciousness",
        "hi": "दौरे या बेहोशी",
        "mr": "आकडी किंवा बेशुद्ध होणे",
        "ta": "வலிப்பு அல்லது நினைவிழப்பு",
    },
    "cough": {
        "en": "Cough",
        "hi": "खांसी",
        "mr": "खोकला",
        "ta": "இருமல்",
    },
    "decreased_or_absent_foetal_movements": {
        "en": "Baby's movements reduced or stopped",
        "hi": "बच्चे की हलचल कम या बंद हो गई",
        "mr": "बाळाची हालचाल कमी झाली किंवा बंद पडली",
        "ta": "குழந்தையின் அசைவு குறைந்துள்ளது அல்லது நின்றுவிட்டது",
    },
    "diarrhea": {
        "en": "Diarrhea / loose motions",
        "hi": "दस्त / लूज मोशन",
        "mr": "जुलाब",
        "ta": "வயிற்றுப்போக்கு",
    },
    "difficult_breathing": {
        "en": "Difficult breathing",
        "hi": "सांस लेने में कठिनाई",
        "mr": "श्वास घेण्यास अडचण",
        "ta": "சுவாசிக்க கடினமாக உள்ளது",
    },
    "drug_overdose_or_poisoning_with_stable_vitals": {
        "en": "Drug overdose or poisoning (vitals stable)",
        "hi": "दवाई की अधिक मात्रा या जहर (जीवन-संकेत स्थिर)",
        "mr": "औषधाचा अतिरिक्त डोस किंवा विषबाधा (जीवनचिन्हे स्थिर)",
        "ta": "மருந்து அதிகமாக உட்கொண்டது அல்லது விஷம் (உடல்நிலை நிலையானது)",
    },
    "ear_pain": {
        "en": "Ear pain",
        "hi": "कान में दर्द",
        "mr": "कानात दुखणे",
        "ta": "காது வலி",
    },
    "ear_problem_reported": {
        "en": "Ear problem reported",
        "hi": "कान की समस्या बताई गई",
        "mr": "कानाची समस्या नोंदवली",
        "ta": "காது பிரச்சனை தெரிவிக்கப்பட்டது",
    },
    "excessive_vomiting_unable_to_take_orally": {
        "en": "Vomiting so much can't keep anything down",
        "hi": "इतनी उल्टी कि कुछ भी नहीं पच रहा",
        "mr": "इतकी उलटी की काहीही पोटात राहत नाही",
        "ta": "வாந்தி மிகவும் அதிகமாக உள்ளது, எதுவும் வயிற்றில் தங்குவதில்லை",
    },
    "fast_or_difficult_breathing": {
        "en": "Fast or difficult breathing",
        "hi": "तेज या मुश्किल सांस",
        "mr": "जलद किंवा कठीण श्वास",
        "ta": "வேகமான அல்லது கடினமான சுவாசம்",
    },
    "fever": {
        "en": "Fever",
        "hi": "बुखार",
        "mr": "ताप",
        "ta": "காய்ச்சல்",
    },
    "fever_in_chemo_or_hiv_or_diabetic_patient": {
        "en": "Fever in a patient with cancer/HIV/diabetes",
        "hi": "कैंसर/HIV/मधुमेह रोगी में बुखार",
        "mr": "कर्करोग/HIV/मधुमेह असलेल्या रुग्णाला ताप",
        "ta": "புற்றுநோய்/HIV/நீரிழிவு நோயாளிக்கு காய்ச்சல்",
    },
    "fever_under_101f": {
        "en": "Mild fever (below 101°F / 38.3°C)",
        "hi": "हल्का बुखार (101°F से कम)",
        "mr": "सौम्य ताप (101°F पेक्षा कमी)",
        "ta": "லேசான காய்ச்சல் (101°F-க்கும் குறைவானது)",
    },
    "fever_with_headache_or_chest_pain_or_jaundice": {
        "en": "Fever with headache, chest pain, or jaundice",
        "hi": "बुखार के साथ सिरदर्द, सीने में दर्द, या पीलिया",
        "mr": "तापासोबत डोकेदुखी, छातीत दुखणे किंवा कावीळ",
        "ta": "காய்ச்சலுடன் தலைவலி, மார்பு வலி, அல்லது மஞ்சள் காமாலை",
    },
    "fits": {
        "en": "Fits / seizures",
        "hi": "दौरे",
        "mr": "झटके",
        "ta": "வலிப்பு",
    },
    "foul_smelling_discharge": {
        "en": "Foul-smelling discharge after delivery",
        "hi": "प्रसव के बाद बदबूदार स्राव",
        "mr": "प्रसूतीनंतर दुर्गंधीयुक्त स्राव",
        "ta": "பிரசவத்திற்கு பிறகு துர்நாற்றமுள்ள வெளியீடு",
    },
    "fracture_of_hand_or_feet": {
        "en": "Fracture of hand or foot",
        "hi": "हाथ या पैर की हड्डी टूटना",
        "mr": "हात किंवा पायाचे हाड तुटणे",
        "ta": "கை அல்லது கால் எலும்பு முறிவு",
    },
    "fracture_with_exposed_bone": {
        "en": "Fracture with bone sticking out",
        "hi": "हड्डी बाहर निकली हुई फ्रैक्चर",
        "mr": "हाड बाहेर आलेले अस्थिभंग",
        "ta": "எலும்பு வெளியே தெரியும் முறிவு",
    },
    "fresh_scratches_or_wounds": {
        "en": "Fresh scratches or minor wounds",
        "hi": "ताजी खरोंच या छोटे घाव",
        "mr": "ताजे ओरखडे किंवा लहान जखमा",
        "ta": "புதிய கீறல்கள் அல்லது சிறிய காயங்கள்",
    },
    "haemoglobin_7_to_11_despite_30_days_ifa": {
        "en": "Haemoglobin 7–11 despite taking iron tablets for 30 days",
        "hi": "30 दिन आयरन की गोलियां लेने के बाद भी Hb 7–11",
        "mr": "30 दिवस लोह गोळ्या घेऊनही Hb 7–11",
        "ta": "30 நாட்கள் இரும்புச்சத்து மாத்திரை சாப்பிட்டும் Hb 7–11",
    },
    "haemoglobin_lt_7": {
        "en": "Haemoglobin below 7 (severe anaemia)",
        "hi": "Hb 7 से कम (गंभीर एनीमिया)",
        "mr": "Hb 7 पेक्षा कमी (तीव्र अशक्तपणा)",
        "ta": "Hb 7-க்கும் குறைவு (தீவிர இரத்த சோகை)",
    },
    "hanging_or_near_drowning_or_electrocution_or_heat_stroke": {
        "en": "Hanging, near-drowning, electric shock, or heat stroke",
        "hi": "फांसी, डूबते-डूबते बचना, बिजली का झटका, या लू लगना",
        "mr": "गळफास, बुडण्यापासून बचाव, वीज लागणे, किंवा उष्माघात",
        "ta": "தூக்கிலிடப்பட்டது, மூழ்கியது, மின்சார அதிர்ச்சி, அல்லது வெப்ப பக்கவாதம்",
    },
    "headache_or_dizziness": {
        "en": "Headache or dizziness",
        "hi": "सिरदर्द या चक्कर",
        "mr": "डोकेदुखी किंवा चक्कर",
        "ta": "தலைவலி அல்லது தலைச்சுற்றல்",
    },
    "high_bp_gt_140_90_with_or_without_proteinuria": {
        "en": "High blood pressure (≥140/90) with or without protein in urine",
        "hi": "उच्च रक्तचाप (≥140/90) पेशाब में प्रोटीन के साथ या बिना",
        "mr": "उच्च रक्तदाब (≥140/90) मूत्रात प्रथिने असो वा नसो",
        "ta": "உயர் இரத்த அழுத்தம் (≥140/90) சிறுநீரில் புரதத்துடன் அல்லது இல்லாமல்",
    },
    "high_fever_with_or_without_abdominal_pain_too_weak_to_get_out_of_bed": {
        "en": "High fever, too weak to get out of bed (with or without stomach pain)",
        "hi": "तेज बुखार, बिस्तर से उठने में असमर्थ",
        "mr": "तीव्र ताप, अंथरुणातून उठण्यास असमर्थ",
        "ta": "அதிக காய்ச்சல், படுக்கையில் இருந்து எழுந்திரிக்க முடியவில்லை",
    },
    "high_grade_fever_with_altered_mental_status": {
        "en": "Very high fever with confusion or altered mental status",
        "hi": "बहुत तेज बुखार के साथ भ्रम या असामान्य मानसिक स्थिति",
        "mr": "अत्यंत तीव्र तापासोबत गोंधळ",
        "ta": "மிக அதிக காய்ச்சலுடன் குழப்பம்",
    },
    "history_of_fainting_or_syncope": {
        "en": "History of fainting or blacking out",
        "hi": "बेहोश होने का इतिहास",
        "mr": "बेशुद्ध होण्याचा इतिहास",
        "ta": "மயக்கம் வந்த வரலாறு",
    },
    "injury": {
        "en": "Injury (during pregnancy)",
        "hi": "चोट (गर्भावस्था के दौरान)",
        "mr": "दुखापत (गर्भावस्थेदरम्यान)",
        "ta": "காயம் (கர்ப்பகாலத்தில்)",
    },
    "isolated_long_bone_fracture": {
        "en": "Single broken long bone (arm or leg)",
        "hi": "एकल बड़ी हड्डी टूटना (हाथ या पैर)",
        "mr": "एकट्या मोठ्या हाडाचे अस्थिभंग",
        "ta": "ஒற்றை நீண்ட எலும்பு முறிவு (கை அல்லது கால்)",
    },
    "lethargic_or_unconscious": {
        "en": "Very drowsy, limp, or unconscious",
        "hi": "बहुत सुस्त, ढीला, या बेहोश",
        "mr": "खूप सुस्त, शिथिल किंवा बेशुद्ध",
        "ta": "மிகவும் தூக்கமாக, தளர்ந்து, அல்லது நினைவிழந்து",
    },
    "limb_injury_with_absent_distal_pulse": {
        "en": "Arm or leg injury with no pulse below the injury",
        "hi": "हाथ या पैर की चोट में चोट के नीचे नाड़ी नहीं",
        "mr": "हात किंवा पाय दुखापत ज्यात दुखापतीखाली नाडी नाही",
        "ta": "கை அல்லது கால் காயத்தில் காயத்தின் கீழ் நாடி இல்லை",
    },
    "liquor_colour_green_or_brown": {
        "en": "Waters / amniotic fluid is green or brown",
        "hi": "पानी / एम्नियोटिक तरल हरा या भूरा है",
        "mr": "पाणी / अम्नियोटिक द्रव हिरवे किंवा तपकिरी आहे",
        "ta": "பனிக்குட நீர் பச்சை அல்லது பழுப்பு நிறத்தில் உள்ளது",
    },
    "loss_of_foetal_movement_or_severe_abdominal_pain": {
        "en": "Baby not moving or severe stomach pain",
        "hi": "बच्चा नहीं हिल रहा या तेज पेट दर्द",
        "mr": "बाळ हलत नाही किंवा तीव्र पोटदुखी",
        "ta": "குழந்தை அசையவில்லை அல்லது கடுமையான வயிற்று வலி",
    },
    "low_risk_cough_or_cold": {
        "en": "Mild cough or cold (low risk)",
        "hi": "हल्की खांसी या सर्दी (कम जोखिम)",
        "mr": "सौम्य खोकला किंवा सर्दी (कमी जोखीम)",
        "ta": "லேசான இருமல் அல்லது சளி (குறைந்த ஆபத்து)",
    },
    "malaria_test_negative": {
        "en": "Malaria test negative",
        "hi": "मलेरिया परीक्षण नकारात्मक",
        "mr": "मलेरिया चाचणी नकारात्मक",
        "ta": "மலேரியா சோதனை எதிர்மறை",
    },
    "malaria_test_positive": {
        "en": "Malaria test positive",
        "hi": "मलेरिया परीक्षण सकारात्मक",
        "mr": "मलेरिया चाचणी सकारात्मक",
        "ta": "மலேரியா சோதனை நேர்மறை",
    },
    "malpresentation": {
        "en": "Baby in wrong position (malpresentation)",
        "hi": "बच्चा गलत स्थिति में है",
        "mr": "बाळ चुकीच्या स्थितीत आहे",
        "ta": "குழந்தை தவறான நிலையில் உள்ளது",
    },
    "mild_cough": {
        "en": "Mild cough",
        "hi": "हल्की खांसी",
        "mr": "सौम्य खोकला",
        "ta": "லேசான இருமல்",
    },
    "minor_head_injury": {
        "en": "Minor head injury",
        "hi": "सिर पर मामूली चोट",
        "mr": "डोक्याला किरकोळ दुखापत",
        "ta": "சிறிய தலை காயம்",
    },
    "minor_symptoms_of_existing_illness": {
        "en": "Mild symptoms of an existing known illness",
        "hi": "मौजूदा बीमारी के हल्के लक्षण",
        "mr": "विद्यमान आजाराची सौम्य लक्षणे",
        "ta": "இருக்கும் நோயின் லேசான அறிகுறிகள்",
    },
    "more_than_5_pads_per_day_or_1_thick_cloth_per_day": {
        "en": "More than 5 pads soaked per day (after delivery)",
        "hi": "प्रसव के बाद प्रतिदिन 5 से अधिक पैड भीगना",
        "mr": "प्रसूतीनंतर दिवसाला 5 पेक्षा जास्त पॅड भिजणे",
        "ta": "பிரசவத்திற்கு பிறகு நாளொன்றுக்கு 5-க்கும் மேற்பட்ட பேட் நனைகிறது",
    },
    "movement_only_when_stimulated_or_none": {
        "en": "Baby / infant moves only when touched, or not at all",
        "hi": "बच्चा केवल छूने पर हिलता है या बिल्कुल नहीं",
        "mr": "बाळ फक्त स्पर्श केल्यावरच हलते किंवा अजिबात नाही",
        "ta": "குழந்தை தொட்டால் மட்டுமே அசைகிறது, அல்லது அசையவேயில்லை",
    },
    "multiple_injuries": {
        "en": "Multiple injuries",
        "hi": "कई चोटें",
        "mr": "अनेक दुखापती",
        "ta": "பல காயங்கள்",
    },
    "multiple_pregnancy": {
        "en": "Twins or more (multiple pregnancy)",
        "hi": "जुड़वां या अधिक (बहु-गर्भावस्था)",
        "mr": "जुळे किंवा अधिक (बहु-गर्भधारणा)",
        "ta": "இரட்டையர் அல்லது அதிகமானோர் (பல கர்ப்பம்)",
    },
    "noisy_breathing_or_stridor": {
        "en": "Noisy breathing / stridor",
        "hi": "शोर वाली सांस / स्ट्रिडोर",
        "mr": "आवाजी श्वास / स्ट्रिडोर",
        "ta": "சத்தமான சுவாசம் / ஸ்ட்ரிடோர்",
    },
    "not_able_to_drink_or_drinking_poorly": {
        "en": "Unable to drink or drinking very poorly",
        "hi": "पीने में असमर्थ या बहुत कम पी रहा है",
        "mr": "पिण्यास असमर्थ किंवा खूप कमी पिणे",
        "ta": "குடிக்க முடியவில்லை அல்லது மிகவும் கொஞ்சமாக குடிக்கிறது",
    },
    "not_able_to_drink_or_feed": {
        "en": "Unable to drink or feed (infant)",
        "hi": "दूध पीने या खाने में असमर्थ (शिशु)",
        "mr": "दूध पिण्यास किंवा खाण्यास असमर्थ (अर्भक)",
        "ta": "குழந்தை குடிக்கவோ சாப்பிடவோ முடியவில்லை",
    },
    "ongoing_bleeding_vomitus_cough_urine_or_nose": {
        "en": "Ongoing bleeding from vomit, cough, urine, or nose",
        "hi": "उल्टी, खांसी, पेशाब, या नाक से लगातार खून",
        "mr": "उलटी, खोकला, लघवी किंवा नाकातून सतत रक्त",
        "ta": "வாந்தி, இருமல், சிறுநீர், அல்லது மூக்கில் இருந்து தொடர்ந்து இரத்தம்",
    },
    "painful_bleeding_per_rectum": {
        "en": "Painful bleeding from rectum",
        "hi": "मलद्वार से दर्दनाक रक्तस्राव",
        "mr": "मलमार्गातून वेदनादायक रक्तस्राव",
        "ta": "மலத்திலிருந்து வலிமிகுந்த இரத்தப்போக்கு",
    },
    "painful_swelling_or_wound": {
        "en": "Painful swelling or wound",
        "hi": "दर्दनाक सूजन या घाव",
        "mr": "वेदनादायक सूज किंवा जखम",
        "ta": "வலிமிகுந்த வீக்கம் அல்லது காயம்",
    },
    "pallor_or_known_anaemia_needing_transfusion": {
        "en": "Very pale (anaemia) needing blood transfusion",
        "hi": "बहुत पीलापन (एनीमिया) जिसे रक्त आधान की जरूरत हो",
        "mr": "खूप फिकेपणा (अशक्तपणा) ज्याला रक्त संक्रमणाची गरज आहे",
        "ta": "மிகவும் வெளிறிய தோற்றம் (இரத்த சோகை) இரத்தமாற்றம் தேவை",
    },
    "pallor_with_breathlessness_or_foot_swelling": {
        "en": "Paleness with breathlessness or swollen feet",
        "hi": "पीलापन के साथ सांस फूलना या पैरों में सूजन",
        "mr": "फिकेपणासोबत श्वास लागणे किंवा पायांना सूज",
        "ta": "வெளிறிய தோற்றத்துடன் மூச்சுத் திணறல் அல்லது கால் வீக்கம்",
    },
    "post_seizure_stage": {
        "en": "Just had a seizure / fit (post-ictal)",
        "hi": "अभी-अभी दौरा आया",
        "mr": "नुकताच झटका आला",
        "ta": "இப்போது வலிப்பு வந்தது",
    },
    "premature_rupture_of_membranes_before_37_weeks": {
        "en": "Water broke before 37 weeks of pregnancy",
        "hi": "37 सप्ताह से पहले पानी की थैली फटना",
        "mr": "37 आठवड्यांपूर्वी पाण्याची थैली फुटणे",
        "ta": "37 வாரங்களுக்கு முன் பனிக்குட நீர் உடைந்தது",
    },
    "prolonged_labour_pushing_gt_12h_or_gt_8h_multipara": {
        "en": "Labour pushing for more than 12 hours (8 hours for mothers with prior births)",
        "hi": "12 घंटे से अधिक प्रसव पीड़ा (पहले जन्म दे चुकी माताओं में 8 घंटे से अधिक)",
        "mr": "12 तासांपेक्षा जास्त काळ प्रसव वेदना",
        "ta": "12 மணி நேரத்திற்கும் மேலாக பிரசவ வலி",
    },
    "pus_draining_14_days_or_more": {
        "en": "Pus draining from ear for 14 days or more",
        "hi": "14 दिन या अधिक से कान से पस निकलना",
        "mr": "14 दिवस किंवा अधिक काळ कानातून पू येणे",
        "ta": "14 நாட்கள் அல்லது அதிகமாக காதில் இருந்து சீழ் வடிகிறது",
    },
    "pus_draining_less_than_14_days": {
        "en": "Pus draining from ear for less than 14 days",
        "hi": "14 दिन से कम से कान से पस निकलना",
        "mr": "14 दिवसांपेक्षा कमी काळ कानातून पू येणे",
        "ta": "14 நாட்களுக்கும் குறைவாக காதில் இருந்து சீழ் வடிகிறது",
    },
    "reduced_urinary_output_with_high_bp": {
        "en": "Less urine than normal along with high blood pressure",
        "hi": "उच्च रक्तचाप के साथ सामान्य से कम पेशाब",
        "mr": "उच्च रक्तदाबासोबत सामान्यपेक्षा कमी लघवी",
        "ta": "உயர் இரத்த அழுத்தத்துடன் சாதாரணத்தை விட குறைவான சிறுநீர்",
    },
    "retained_placenta": {
        "en": "Placenta not delivered after birth",
        "hi": "प्रसव के बाद नाल नहीं निकली",
        "mr": "प्रसूतीनंतर वार बाहेर आली नाही",
        "ta": "பிரசவத்திற்கு பிறகு நஞ்சுக்கொடி வெளியே வரவில்லை",
    },
    "ruptured_membranes_more_than_18h": {
        "en": "Water broke more than 18 hours ago",
        "hi": "18 घंटे से अधिक पहले पानी की थैली फट गई",
        "mr": "18 तासांपेक्षा जास्त वेळापूर्वी पाण्याची थैली फुटली",
        "ta": "18 மணி நேரத்திற்கும் முன்பே பனிக்குட நீர் உடைந்தது",
    },
    "runny_nose": {
        "en": "Runny nose",
        "hi": "नाक बहना",
        "mr": "नाक वाहणे",
        "ta": "மூக்கு ஒழுகுவது",
    },
    "severe_headache": {
        "en": "Severe headache",
        "hi": "तेज सिरदर्द",
        "mr": "तीव्र डोकेदुखी",
        "ta": "கடுமையான தலைவலி",
    },
    "severe_headache_with_blurred_vision_or_spots": {
        "en": "Severe headache with blurred vision or seeing spots",
        "hi": "धुंधली दृष्टि या धब्बों के साथ तेज सिरदर्द",
        "mr": "अंधुक दृष्टी किंवा ठिपके दिसण्यासोबत तीव्र डोकेदुखी",
        "ta": "மங்கலான பார்வை அல்லது புள்ளிகள் தெரிவதுடன் கடுமையான தலைவலி",
    },
    "simple_skin_rash": {
        "en": "Simple skin rash",
        "hi": "साधारण त्वचा पर दाने",
        "mr": "साधारण त्वचेवर पुरळ",
        "ta": "சாதாரண தோல் தடிப்பு",
    },
    "skin_pinch_goes_back_very_slowly": {
        "en": "Skin stays pinched (returns very slowly — sign of dehydration)",
        "hi": "त्वचा चुटकी लेने के बाद बहुत धीरे-धीरे वापस आती है (निर्जलीकरण का संकेत)",
        "mr": "त्वचा चिमटा काढल्यावर खूप हळू परत येते (निर्जलीकरणाचे लक्षण)",
        "ta": "தோலை கிள்ளினால் மிகவும் மெதுவாக திரும்புகிறது (நீர்ச்சத்து குறைபாட்டின் அறிகுறி)",
    },
    "snake_or_scorpion_bite": {
        "en": "Snake or scorpion bite",
        "hi": "सांप या बिच्छू का काटना",
        "mr": "साप किंवा विंचू चावणे",
        "ta": "பாம்பு அல்லது தேள் கடித்தது",
    },
    "stab_or_penetrating_injury": {
        "en": "Stab wound or puncture injury",
        "hi": "छुरा मारना या छेदने वाली चोट",
        "mr": "भोसकण्याची जखम किंवा छेदणारी दुखापत",
        "ta": "கத்தி காயம் அல்லது குத்து காயம்",
    },
    "stiff_neck": {
        "en": "Stiff neck",
        "hi": "गर्दन में अकड़न",
        "mr": "मान कडक होणे",
        "ta": "கழுத்து விறைப்பு",
    },
    "stroke_fast_signs": {
        "en": "Stroke signs: Face drooping, Arm weak, Speech slurred (FAST)",
        "hi": "स्ट्रोक के लक्षण: चेहरा लटकना, हाथ कमज़ोर, बोलने में गड़बड़ी",
        "mr": "स्ट्रोकची लक्षणे: चेहरा झुकणे, हात कमकुवत, बोलण्यात अडचण",
        "ta": "பக்கவாத அறிகுறிகள்: முகம் தொங்குதல், கை பலவீனம், பேச்சு குழறுதல்",
    },
    "subcutaneous_crackles_or_seatbelt_mark": {
        "en": "Crackles under skin or seatbelt mark on chest",
        "hi": "त्वचा के नीचे कड़कड़ाहट या छाती पर सीट बेल्ट का निशान",
        "mr": "त्वचेखाली कुरकुरण्याचा आवाज किंवा छातीवर सीट बेल्टचा निशान",
        "ta": "தோலின் கீழ் சத்தம் அல்லது மார்பில் சீட்பெல்ட் தழும்பு",
    },
    "sunken_eyes": {
        "en": "Sunken eyes",
        "hi": "आंखें धंसी हुई",
        "mr": "डोळे खोल गेलेले",
        "ta": "கண்கள் உள்ளே இழுத்துக்கொண்டிருக்கின்றன",
    },
    "suspected_neck_injury": {
        "en": "Suspected neck injury",
        "hi": "गर्दन की चोट की आशंका",
        "mr": "मानेला दुखापत झाल्याची शंका",
        "ta": "கழுத்து காயம் சந்தேகம்",
    },
    "suspected_poisoning_with_unstable_vitals": {
        "en": "Suspected poisoning with unstable vital signs",
        "hi": "संदिग्ध विषाक्तता अस्थिर जीवन संकेतों के साथ",
        "mr": "अस्थिर जीवनचिन्हांसह संशयित विषबाधा",
        "ta": "நிலையற்ற உடல்நிலை அறிகுறிகளுடன் நச்சு சந்தேகம்",
    },
    "suspected_sexual_assault": {
        "en": "Suspected sexual assault",
        "hi": "यौन उत्पीड़न की आशंका",
        "mr": "लैंगिक अत्याचाराची शंका",
        "ta": "பாலியல் வன்கொடுமை சந்தேகம்",
    },
    "suspected_spine_injury": {
        "en": "Suspected spine injury",
        "hi": "रीढ़ की हड्डी में चोट की आशंका",
        "mr": "पाठीच्या कण्याला दुखापत झाल्याची शंका",
        "ta": "முதுகுத் தண்டு காயம் சந்தேகம்",
    },
    "swelling_face_or_hands": {
        "en": "Swelling of face or hands",
        "hi": "चेहरे या हाथों में सूजन",
        "mr": "चेहरा किंवा हातांना सूज",
        "ta": "முகம் அல்லது கைகளில் வீக்கம்",
    },
    "swollen_face_or_hands": {
        "en": "Swollen face or hands",
        "hi": "चेहरे या हाथों में सूजन",
        "mr": "चेहरा किंवा हात सुजलेले",
        "ta": "முகம் அல்லது கைகள் வீங்கியுள்ளன",
    },
    "swollen_face_or_hands_pitting_oedema": {
        "en": "Swollen face or hands / pitting oedema (finger leaves dent)",
        "hi": "चेहरे या हाथों में सूजन / पिटिंग ओडेमा (उंगली दबाने पर निशान रहता है)",
        "mr": "चेहरा किंवा हात सुजलेले / पिटिंग ओडेमा (बोट दाबल्यावर खड्डा राहतो)",
        "ta": "முகம் அல்லது கைகளில் வீக்கம் / பிட்டிங் ஈடிமா (விரலால் அழுத்தினால் குழி விழுகிறது)",
    },
    "tender_swelling_behind_ear": {
        "en": "Tender / painful swelling behind the ear",
        "hi": "कान के पीछे दर्दनाक सूजन",
        "mr": "कानामागे वेदनादायक सूज",
        "ta": "காதுக்கு பின்னால் வலிமிகுந்த வீக்கம்",
    },
    "two_or_more_long_bone_fractures": {
        "en": "Two or more broken long bones",
        "hi": "दो या अधिक बड़ी हड्डियां टूटना",
        "mr": "दोन किंवा अधिक मोठ्या हाडांचे अस्थिभंग",
        "ta": "இரண்டு அல்லது அதிகமான நீண்ட எலும்பு முறிவுகள்",
    },
    "unable_to_pass_stool": {
        "en": "Unable to pass stool / constipation",
        "hi": "मल त्याग में असमर्थ / कब्ज",
        "mr": "शौच करण्यास असमर्थ / बद्धकोष्ठता",
        "ta": "மலம் கழிக்க முடியவில்லை / மலச்சிக்கல்",
    },
    "unable_to_pass_urine": {
        "en": "Unable to pass urine",
        "hi": "पेशाब करने में असमर्थ",
        "mr": "लघवी करण्यास असमर्थ",
        "ta": "சிறுநீர் கழிக்க முடியவில்லை",
    },
    "vomiting": {
        "en": "Vomiting",
        "hi": "उल्टी",
        "mr": "उलटी",
        "ta": "வாந்தி",
    },
    "vomits_everything": {
        "en": "Vomits everything — can't keep anything down",
        "hi": "सब उल्टी कर देता है — कुछ भी नहीं पचता",
        "mr": "सर्व उलटी होते — काहीही पोटात राहत नाही",
        "ta": "எல்லாவற்றையும் வாந்தி எடுக்கிறது",
    },
    "water_broke_no_labour_within_24h": {
        "en": "Water broke but no labour contractions within 24 hours",
        "hi": "पानी की थैली फट गई लेकिन 24 घंटे में प्रसव पीड़ा नहीं",
        "mr": "पाण्याची थैली फुटली पण 24 तासात प्रसव वेदना नाही",
        "ta": "பனிக்குட நீர் உடைந்தது ஆனால் 24 மணி நேரத்தில் பிரசவ வலி இல்லை",
    },
    "dark_or_cola_coloured_urine": {
        "en": "Dark or cola-coloured urine",
        "hi": "गहरे या कोला रंग का पेशाब",
        "mr": "गडद किंवा कोला रंगाची लघवी",
        "ta": "கருமை அல்லது கோலா நிற சிறுநீர்",
    },
    "chills_and_rigors": {
        "en": "Chills and shivering / rigors",
        "hi": "ठंड लगना और कंपकंपी",
        "mr": "थंडी वाजून येणे आणि थरथरणे",
        "ta": "குளிர் மற்றும் நடுக்கம்",
    },
    "fever_with_chills": {
        "en": "Fever with chills",
        "hi": "ठंड के साथ बुखार",
        "mr": "थंडीसह ताप",
        "ta": "குளிருடன் காய்ச்சல்",
    },
    "persistent_vomiting": {
        "en": "Persistent vomiting",
        "hi": "लगातार उल्टी होना",
        "mr": "सतत उलटी होणे",
        "ta": "தொடர் வாந்தி",
    },
    "persistent_or_severe_abdominal_pain_or_tenderness": {
        "en": "Persistent severe stomach pain or tenderness",
        "hi": "लगातार तेज पेट दर्द या छूने पर दर्द",
        "mr": "सतत तीव्र पोटदुखी किंवा दाबल्यावर दुखणे",
        "ta": "தொடர்ச்சியான கடுமையான வயிற்று வலி",
    },
    "restlessness_or_sudden_behavioral_change": {
        "en": "Restlessness or sudden behavioral change",
        "hi": "बेचैनी या व्यवहार में अचानक बदलाव",
        "mr": "अस्वस्थता किंवा वर्तनात अचानक बदल",
        "ta": "அமைதியின்மை அல்லது திடீர் நடத்தை மாற்றம்",
    },
    "abdominal_distension_or_swelling": {
        "en": "Stomach bloating / abdominal distension",
        "hi": "पेट फूलना या सूजन",
        "mr": "पोट फुगणे किंवा सूज",
        "ta": "வயிறு வீக்கம்",
    },
    "cough_more_than_2_weeks": {
        "en": "Cough lasting more than 2 weeks",
        "hi": "2 सप्ताह से अधिक समय से खांसी",
        "mr": "२ आठवड्यांपेक्षा जास्त काळ खोकला",
        "ta": "2 வாரங்களுக்கும் மேலாக இருமல்",
    },
    "fever_more_than_2_weeks": {
        "en": "Fever lasting more than 2 weeks",
        "hi": "2 सप्ताह से अधिक समय से बुखार",
        "mr": "२ आठवड्यांपेक्षा जास्त काळ ताप",
        "ta": "2 வாரங்களுக்கும் மேலாக காய்ச்சல்",
    },
    "significant_weight_loss": {
        "en": "Significant unexplained weight loss",
        "hi": "वजन में अप्रत्याशित भारी गिरावट",
        "mr": "अचानक वजन खूप कमी होणे",
        "ta": "குறிப்பிடத்தக்க எடை இழப்பு",
    },
    "contact_with_known_tb_patient": {
        "en": "Contact with a known TB patient",
        "hi": "टीबी के मरीज के संपर्क में आना",
        "mr": "टीबी (क्षयरोग) रुग्णाच्या संपर्कात येणे",
        "ta": "காசநோய் (TB) நோயாளியுடன் தொடர்பு",
    },
    "pallor_or_pale_skin_or_conjunctiva": {
        "en": "Pale skin, tongue, or inner eyelids (Pallor)",
        "hi": "त्वचा, जीभ या आंखों में पीलापन (फीकापन)",
        "mr": "त्वचा, जीभ किंवा डोळ्यांत फिकेपणा",
        "ta": "வெளிறிய தோல், நாக்கு அல்லது கண் இமைகள்",
    },
    "pallor": {
        "en": "Pale appearance / Pallor",
        "hi": "पीलापन / फीकापन",
        "mr": "फिकेपणा",
        "ta": "வெளிறிய தோற்றம்",
    },
}
