/**
 * src/constants/symptoms.ts
 *
 * Frontline ASHA Screening Symptom Catalog.
 * Aligned with IMNCI, ASHA Module 6, SBA Box 7, and Common Emergencies.
 */

import { Language } from "../types";

export interface SymptomItem {
  id: string;
  isDangerSign: boolean;
  category: "danger" | "respiratory" | "fever" | "digestive" | "maternal" | "adult_emergency" | "ear";
  labels: Record<Language, string>;
  description: Record<Language, string>;
  applicableSex?: "female" | "all";
  onlyPregnantOrPostpartum?: boolean;
}

export const ASHA_SYMPTOMS: SymptomItem[] = [
  {
    id: "not_able_to_drink_or_feed",
    isDangerSign: true,
    category: "danger",
    labels: {
      mr: "दूध किंवा पाणी पिण्यास असमर्थ",
      hi: "दूध या पानी पीने में असमर्थ",
      en: "Unable to drink or feed",
      ta: "பால் அல்லது தண்ணீர் குடிக்க இயலாமை",
    },
    description: {
      mr: "मूल किंवा रुग्ण काहीही पिऊ शकत नाही",
      hi: "मरीज कुछ भी पी या खा नहीं पा रहा",
      en: "Patient cannot retain any fluids or breastfeed",
      ta: "திரவங்களை உட்கொள்ள இயலாத நிலை",
    },
  },
  {
    id: "vomits_everything",
    isDangerSign: true,
    category: "danger",
    labels: {
      mr: "खाल्लेले सर्व उलटून पडणे",
      hi: "खाया-पिया सब कुछ उल्टी होना",
      en: "Vomiting everything",
      ta: "சாப்பிட்ட அனைத்தும் வாந்தியாகுதல்",
    },
    description: {
      mr: "पाणीही पोटात राहत नाही",
      hi: "पानी भी पेट में नहीं रुकता",
      en: "Inability to keep anything down",
      ta: "தண்ணீரும் வயிற்றில் தங்காத நிலை",
    },
  },
  {
    id: "convulsions",
    isDangerSign: true,
    category: "danger",
    labels: {
      mr: "झटके, आकडी किंवा फेफरे (Fits)",
      hi: "दौरे या झटके आना (Fits)",
      en: "Convulsions or seizures / fits",
      ta: "வலிப்பு / இழுப்பு / கை கால் உதறல்",
    },
    description: {
      mr: "हात-पाय ताठ होणे किंवा थरथरणे",
      hi: "शरीर अकड़ना या दौरे पड़ना",
      en: "Muscle spasms, jerking, or fits",
      ta: "தசைப்பிடிப்பு மற்றும் நடுக்கம்",
    },
  },
  {
    id: "convulsions_or_loss_of_consciousness",
    isDangerSign: true,
    category: "danger",
    labels: {
      mr: "झटके येणे, आकडी किंवा अचानक बेशुद्ध पडणे",
      hi: "दौरे पड़ना, झटके आना या अचानक बेहोश हो जाना",
      en: "Active convulsions, seizures or sudden loss of consciousness",
      ta: "வலிப்பு அல்லது திடீர் சுயநினைவின்மை",
    },
    description: {
      mr: "तातडीने १०८ रुग्णवाहिका बोलावून रुग्णालयात दाखल करा",
      hi: "आपातकालीन स्थिति - तुरंत 108 बुलाकर अस्पताल रेफर करें",
      en: "Critical central nervous system emergency requiring airway protection and immediate transfer",
      ta: "உடனடி அவசர சிகிச்சை தேவைப்படும் நரம்பியல் ஆபத்து",
    },
  },
  {
    id: "lethargic_or_unconscious",
    isDangerSign: true,
    category: "danger",
    labels: {
      mr: "अतिसुस्त किंवा बेशुद्ध (Unresponsive)",
      hi: "अत्यधिक सुस्त या बेहोश",
      en: "Lethargic, drowsy or unconscious",
      ta: "மயக்கம் அல்லது பதிலளிக்காத நிலை",
    },
    description: {
      mr: "हाक मारल्यावर डोळे उघडत नाही",
      hi: "बुलाने पर भी होश में न आना",
      en: "Does not wake or respond normally",
      ta: "அசைவு அல்லது சுயநினைவற்ற நிலை",
    },
  },
  {
    id: "movement_only_when_stimulated_or_none",
    isDangerSign: true,
    category: "danger",
    labels: {
      mr: "अतिसुस्त, हलवल्यावरच थोडी हालचाल करणे किंवा अजिबात हालचाल नसणे",
      hi: "अत्यधिक सुस्त, हिलाने-डुलाने पर ही हलचल करना या बिल्कुल न हिलना",
      en: "Abnormally sleepy, moves only when stimulated or no movement at all",
      ta: "அசைவற்று இருத்தல் அல்லது தொடும்போது மட்டுமே சிறிதளவு அசைதல்",
    },
    description: {
      mr: "लहान मुलांमधील गंभीर आजार किंवा सेप्सिसचे लक्षण",
      hi: "शिशुओं में गंभीर बीमारी या सेप्सिस का संकेत",
      en: "Severe lethargy or obtundation indicating critical illness in young infants/children",
      ta: "பச்சிளங்குழந்தைகளில் தீவிர நோய்த்தொற்றின் ஆபத்து",
    },
  },
  {
    id: "excessive_vomiting_unable_to_take_orally",
    isDangerSign: true,
    category: "danger",
    labels: {
      mr: "सतत तीव्र उलट्या होणे, तोंडाने काहीही घेणे अशक्य असणे",
      hi: "लगातार अत्यधिक उल्टी, मुंह से कुछ भी लेने में पूरी तरह असमर्थ",
      en: "Excessive continuous vomiting, completely unable to take anything orally",
      ta: "தொடர் கடுமையான வாந்தி, வாயால் எதையும் உட்கொள்ள இயலாமை",
    },
    description: {
      mr: "तीव्र निर्जलीकरण आणि शॉकचा मोठा धोका",
      hi: "तीव्र निर्जलीकरण और शॉक का गंभीर जोखिम",
      en: "Risk of rapid severe dehydration, electrolyte collapse, and shock",
      ta: "தீவிர நீர்ச்சத்து இழப்பு மற்றும் அதிர்ச்சி ஆபத்து",
    },
  },
  {
    id: "breathlessness",
    isDangerSign: true,
    category: "respiratory",
    labels: {
      mr: "तीव्र धाप लागणे / दम लागणे",
      hi: "गंभीर सांस फूलना / दम घुटना",
      en: "Severe breathlessness / shortness of breath",
      ta: "கடுமையான மூச்சுத்திணறல்",
    },
    description: {
      mr: "बसल्या जागीही श्वास घेताना त्रास",
      hi: "बैठे-बैठे भी सांस फूलना",
      en: "Severe breathing difficulty even at rest",
      ta: "ஓய்விலும் மூச்சு விட சிரமம்",
    },
  },
  {
    id: "chest_indrawing",
    isDangerSign: true,
    category: "respiratory",
    labels: {
      mr: "श्वास घेताना छाती आत ओढली जाणे",
      hi: "सांस लेते समय छाती अंदर धंसना",
      en: "Chest indrawing (Lower chest sucks in)",
      ta: "மார்பு உள்வாங்குதல்",
    },
    description: {
      mr: "श्वास आत घेताना छातीचा खालचा भाग आत जातो",
      hi: "सांस अंदर खींचने पर छाती धंसती है",
      en: "Lower chest wall pulls inward on inhalation",
      ta: "சுவாசத்தின் போது மார்பு உள்நோக்கி இழுக்கப்படுதல்",
    },
  },
  {
    id: "abnormal_chest_wall_movement_on_breathing",
    isDangerSign: true,
    category: "respiratory",
    labels: {
      mr: "श्वास घेताना छातीच्या पिंजऱ्याची असामान्य किंवा उलटी हालचाल",
      hi: "सांस लेते समय छाती की असामान्य या उलटी हलचल (Flail chest)",
      en: "Abnormal or paradoxical chest wall movement while breathing",
      ta: "சுவாசத்தின் போது மார்பு கூட்டின் வழக்கத்திற்கு மாறான அசைவு",
    },
    description: {
      mr: "छातीत गंभीर दुखापत किंवा बरगड्या मोडल्याचे लक्षण",
      hi: "छाती में गंभीर चोट या फ्रैक्चर का संकेत - तुरंत रेफर करें",
      en: "Sign of flail chest or major thoracic trauma requiring oxygen and surgical care",
      ta: "மார்பு கூண்டு எலும்பு முறிவு அல்லது கடுமையான காயம்",
    },
  },
  {
    id: "stridor_in_children",
    isDangerSign: true,
    category: "respiratory",
    labels: {
      mr: "श्वास आत घेताना खरखर आवाज येणे (स्ट्रायडर)",
      hi: "सांस लेते समय सीटी जैसी तेज आवाज (स्ट्रिडोर)",
      en: "Harsh / Crowing Sound When Breathing In (Stridor)",
      ta: "மூச்சை உள்ளிழுக்கும் போது கடுமையான சத்தம் (ஸ்ட்ரைடர்)",
    },
    description: {
      mr: "श्वसनमार्गात अडथळा किंवा तीव्र संसर्गाचे लक्षण",
      hi: "श्वास नली में रुकावट या गंभीर संक्रमण का संकेत",
      en: "Harsh inspiratory sound indicating upper airway obstruction or severe croup",
      ta: "மேல் சுவாசக்குழாய் அடைப்பு அல்லது தீவிர தொற்றின் அறிகுறி",
    },
  },
  {
    id: "difficult_breathing",
    isDangerSign: false,
    category: "respiratory",
    labels: {
      mr: "जलद किंवा जड श्वासोच्छ्वास",
      hi: "तेज या भारी सांस",
      en: "Fast or noisy breathing / Asthma difficulty",
      ta: "வேகமான அல்லது சிரமமான சுவாசம்",
    },
    description: {
      mr: "सामान्य गतीपेक्षा वेगवान श्वास",
      hi: "सामान्य से अधिक गति से सांस",
      en: "Visibly rapid respiratory rate",
      ta: "வழக்கத்தை விட அதிக சுவாச வேகம்",
    },
  },
  {
    id: "cough",
    isDangerSign: false,
    category: "respiratory",
    labels: {
      mr: "खोकला",
      hi: "खांसी",
      en: "Cough",
      ta: "இருமல்",
    },
    description: {
      mr: "खोकला किंवा घसा खवखवणे",
      hi: "खांसी या गले में खराश",
      en: "Persistent or productive cough",
      ta: "தொடர் இருமல்",
    },
  },
  {
    id: "mild_cough",
    isDangerSign: false,
    category: "respiratory",
    labels: {
      mr: "सौम्य खोकला (जलद श्वास किंवा छाती आत न ओढता)",
      hi: "हल्की खांसी (बिना तेज सांस या छाती धंसे)",
      en: "Mild cough (No fast breathing, no chest indrawing)",
      ta: "லேசான இருமல் (வேகமான சுவாசம் இன்றி)",
    },
    description: {
      mr: "साधा खोकला - घरगुती काळजी आणि भरपूर पाणी/पेये द्या",
      hi: "सामान्य सर्दी-खांसी - घरेलू देखभाल और तरल पदार्थ दें",
      en: "Common upper respiratory infection - manage with home fluids and supportive care",
      ta: "சாதாரண சளி இருமல் - வீட்டுப் பராமரிப்பு போதுமானது",
    },
  },
  {
    id: "cold_runny_nose",
    isDangerSign: false,
    category: "respiratory",
    labels: {
      mr: "सर्दी, नाक वाहणे किंवा नाक चोंदणे",
      hi: "सर्दी और नाक बहना / नाक बंद होना",
      en: "Cold and runny nose / Nasal congestion",
      ta: "சளி மற்றும் மூக்கொழுகுதல் / மூக்கடைப்பு",
    },
    description: {
      mr: "सामान्य सर्दी आणि पडसे",
      hi: "सामान्य मौसमी सर्दी",
      en: "Viral rhinitis / common cold without danger signs",
      ta: "சாதாரண சளி மற்றும் மூக்கடைப்பு",
    },
  },
  {
    id: "sore_throat",
    isDangerSign: false,
    category: "respiratory",
    labels: {
      mr: "घसा खवखवणे किंवा गिळताना दुखणे",
      hi: "गले में खराश या निगलने में दर्द",
      en: "Sore throat / Pain while swallowing",
      ta: "தொண்டை வலி / விழுங்குவதில் சிரமம்",
    },
    description: {
      mr: "घशाचा संसर्ग",
      hi: "गले का संक्रमण",
      en: "Pharyngitis or tonsillitis",
      ta: "தொண்டை தொற்று",
    },
  },
  {
    id: "cough_more_than_2_weeks",
    isDangerSign: false,
    category: "respiratory",
    labels: {
      mr: "२ आठवड्यांपेक्षा जास्त काळ खोकला (टीबी संशय)",
      hi: "2 सप्ताह से अधिक समय से लगातार खांसी (टीबी लक्षण)",
      en: "Cough lasting more than 2 weeks (TB Warning)",
      ta: "2 வாரங்களுக்கும் மேலாக நீடிக்கும் இருமல் (காசநோய் அறிகுறி)",
    },
    description: {
      mr: "संभाव्य टीबी (क्षयरोग) चे लक्षण",
      hi: "संभावित टीबी (क्षयरोग) का लक्षण",
      en: "Presumptive pulmonary tuberculosis symptom",
      ta: "சாத்தியமான காசநோய் (TB) அறிகுறி",
    },
  },
  {
    id: "contact_with_known_tb_patient",
    isDangerSign: false,
    category: "respiratory",
    labels: {
      mr: "टीबी रुग्णाच्या संपर्कात येणे",
      hi: "टीबी मरीज के संपर्क में आना",
      en: "Contact with Known TB Patient",
      ta: "காசநோய் உள்ளவருடன் தொடர்பு",
    },
    description: {
      mr: "टीबी रुग्णाच्या निकट सहवासात असणे - प्रतिबंधात्मक तपासणी आवश्यक",
      hi: "टीबी मरीज के करीबी संपर्क में आना - जांच और टीबी निवारक उपचार (TPT) आवश्यक",
      en: "Household or close contact with confirmed pulmonary TB - screen for preventive therapy",
      ta: "காசநோய் பாதித்தவருடன் நேரடி தொடர்பு - பரிசோதனை அவசியம்",
    },
  },
  {
    id: "fever",
    isDangerSign: false,
    category: "fever",
    labels: {
      mr: "ताप (अंग गरम असणे)",
      hi: "बुखार (शरीर गर्म होना)",
      en: "Fever / Elevated body temperature",
      ta: "காய்ச்சல் / ஜுரம்",
    },
    description: {
      mr: "शरीराचे तापमान वाढलेले असणे",
      hi: "शरीर गर्म लगना या थर्मामीटर पर बुखार",
      en: "Recorded or palpable fever",
      ta: "உடல் சூடாக இருத்தல்",
    },
  },
  {
    id: "fever_with_chills",
    isDangerSign: false,
    category: "fever",
    labels: {
      mr: "थंडी वाजून किंवा भरून येणारा ताप",
      hi: "ठंड / कंपकंपी के साथ बुखार",
      en: "Fever with Chills / Shivering",
      ta: "குளிருடன் கூடிய காய்ச்சல் / நடுக்கம்",
    },
    description: {
      mr: "थंडी वाजून येणारा ताप - मलेरिया/डेंग्यू तपासणी करा",
      hi: "कंपकंपी के साथ बुखार - मलेरिया/डेंगू की RDT जांच कराएं",
      en: "Fever accompanied by rigors / chills - test for Malaria / Dengue",
      ta: "நடுக்கத்துடன் கூடிய காய்ச்சல் - மலேரியா பரிசோதனை தேவை",
    },
  },
  {
    id: "high_grade_fever_with_altered_mental_status",
    isDangerSign: true,
    category: "fever",
    labels: {
      mr: "तीव्र ताप आणि सोबत गोंधळलेली मानसिक अवस्था किंवा असंबद्ध बोलणे",
      hi: "तेज बुखार के साथ मानसिक भ्रम, बेहोशी या बहकी-बहकी बातें",
      en: "High-grade fever with altered mental status or confusion",
      ta: "அதிக காய்ச்சலுடன் கூடிய மனக்குழப்பம் அல்லது சுயநினைவு மாற்றம்",
    },
    description: {
      mr: "मेंदूज्वर किंवा सेरेब्रल मलेरियाचा संशय - तातडीने रुग्णालयात दाखल करा",
      hi: "मस्तिष्क मलेरिया या दिमागी बुखार का गंभीर संकेत - तुरंत रेफर करें",
      en: "Suspected cerebral malaria, encephalitis, or septic encephalopathy",
      ta: "மூளைக்காய்ச்சல் அல்லது தீவிர மூளை நச்சுத்தொற்று ஆபத்து",
    },
  },
  {
    id: "high_fever_with_or_without_abdominal_pain_too_weak_to_get_out_of_bed",
    isDangerSign: false,
    category: "fever",
    labels: {
      mr: "तीव्र ताप आणि अंथरुणातून उठू न शकण्याइतका प्रचंड अशक्तपणा",
      hi: "तेज बुखार और अत्यधिक कमजोरी (बिस्तर से उठने में असमर्थ)",
      en: "High fever with prostration (Too weak to get out of bed)",
      ta: "படுக்கையை விட்டு எழ முடியாத அளவுக்கு கடுமையான காய்ச்சல் மற்றும் சோர்வு",
    },
    description: {
      mr: "टायफॉईड किंवा गंभीर संसर्गाचे लक्षण - डॉक्टरांकडून तपासणी आवश्यक",
      hi: "गंभीर संक्रमण या टाइफाइड का संकेत - स्वास्थ्य केंद्र में दिखाएं",
      en: "Systemic toxicity or severe typhoid / rickettsial infection requiring medical review",
      ta: "டைபாய்டு அல்லது தீவிர பாக்டீரியா தொற்றுக்கான வாய்ப்பு",
    },
  },
  {
    id: "dark_or_cola_coloured_urine",
    isDangerSign: false,
    category: "fever",
    labels: {
      mr: "गडद किंवा कोला रंगाची लघवी",
      hi: "गहरे या कोला रंग का पेशाब",
      en: "Dark or Cola-Coloured Urine",
      ta: "கருமையான அல்லது கோலா நிற சிறுநீர்",
    },
    description: {
      mr: "कावीळ, मूत्रपिंडाचा संसर्ग किंवा रक्तपेशी फुटण्याचे लक्षण",
      hi: "काला-पानी बुखार, हीमोग्लोबिन्यूरिया या लिवर-किडनी समस्या का संकेत",
      en: "Sign of hemoglobinuria, acute glomerulonephritis, or severe jaundice/hepatitis",
      ta: "மஞ்சள் காமாலை, சிறுநீரக பாதிப்பு அல்லது தீவிர தொற்று அறிகுறி",
    },
  },
  {
    id: "fever_more_than_2_weeks",
    isDangerSign: false,
    category: "fever",
    labels: {
      mr: "२ आठवड्यांपेक्षा जास्त काळ सतत ताप",
      hi: "2 सप्ताह से अधिक समय से लगातार बुखार",
      en: "Fever lasting more than 2 weeks",
      ta: "2 வாரங்களுக்கும் மேலாக நீடிக்கும் காய்ச்சல்",
    },
    description: {
      mr: "दीर्घकाळ ताप - टीबी/तपासणी आवश्यक",
      hi: "लंबे समय से बुखार - टीबी/जांच की आवश्यकता",
      en: "Prolonged fever requiring TB / systemic workup",
      ta: "நீண்ட கால காய்ச்சல் - பரிசோதனை தேவை",
    },
  },
  {
    id: "stiff_neck",
    isDangerSign: true,
    category: "fever",
    labels: {
      mr: "मान ताठ होणे (Stiff Neck)",
      hi: "गर्दन अकड़ जाना",
      en: "Stiff neck (Unable to flex chin)",
      ta: "கழுத்து விறைப்பு",
    },
    description: {
      mr: "मान वाकवताना असह्य वेदना",
      hi: "गर्दन आगे झुकाने में तेज दर्द",
      en: "Sign of meningitis or central nervous system infection",
      ta: "கழுத்தை முன்னோக்கி வளைக்க இயலாமை",
    },
  },
  {
    id: "malaria_test_positive",
    isDangerSign: false,
    category: "fever",
    labels: {
      mr: "मलेरिया RDT किट पॉझिटिव्ह",
      hi: "मलेरिया RDT किट पॉजिटिव",
      en: "Malaria RDT test positive",
      ta: "மலேரியா RDT உறுதி (பாசிட்டிவ்)",
    },
    description: {
      mr: "आशा सेविकेने केलेल्या किटमध्ये मलेरिया आढळला",
      hi: "किट जांच में मलेरिया पॉजिटिव",
      en: "Confirmed positive rapid test",
      ta: "மலேரியா பரிசோதனையில் தொற்று உறுதி",
    },
  },
  {
    id: "chest_pain",
    isDangerSign: true,
    category: "adult_emergency",
    labels: {
      mr: "छातीत असह्य वेदना / जडपणा (Chest Pain)",
      hi: "सीने में तेज दर्द या दबाव",
      en: "Severe chest pain / Left-arm radiation",
      ta: "மார்பு வலி / நெஞ்சில் பாரம்",
    },
    description: {
      mr: "हार्ट अटॅकचे संभाव्य लक्षण; १०८ ला तात्काळ पाचारण करा",
      hi: "दिल का दौरा संकेत; 108 बुलाएं",
      en: "Suspected acute coronary syndrome / myocardial infarction",
      ta: "மாரடைப்பு அறிகுறி; 108 அழைக்கவும்",
    },
  },
  {
    id: "stroke_fast_signs",
    isDangerSign: true,
    category: "adult_emergency",
    labels: {
      mr: "पक्षाघात/स्ट्रोकची लक्षणे (तोंड वाकडे होणे, हात लुळा पडणे, बोलताना तोतरेपणा)",
      hi: "स्ट्रोक के लक्षण (चेहरा टेढ़ा होना, हाथ में कमजोरी, आवाज लड़खड़ाना)",
      en: "Stroke FAST signs (Face drooping, Arm weakness, Slurred speech)",
      ta: "பக்கவாத அறிகுறிகள் (முகம் ஒருபுறம் கோணுதல், கை பலவீனம், குழப்பமான பேச்சு)",
    },
    description: {
      mr: "तातडीने १०८ रुग्णवाहिका बोलावून सीटी स्कॅन सुविधा असलेल्या रुग्णालयात दाखल करा",
      hi: "आपातकालीन पक्षाघात/स्ट्रोक - तुरंत 108 बुलाकर सीटी स्कैन वाले अस्पताल ले जाएं",
      en: "Acute ischemic/hemorrhagic stroke - immediate golden hour transfer to stroke center",
      ta: "பக்கவாத அவசர சிகிச்சை - உடனடியாக 108 அழைத்து சிடி ஸ்கேன் வசதி உள்ள மருத்துவமனைக்கு செல்லவும்",
    },
  },
  {
    id: "sudden_weakness_face_arm_speech_slurred",
    isDangerSign: true,
    category: "adult_emergency",
    labels: {
      mr: "अचानक तोंड, हात किंवा पायात अशक्तपणा/लुळेपणा येणे किंवा जीभ जड होणे",
      hi: "अचानक चेहरे, हाथ या पैर में कमजोरी या बोली में लड़खड़ाहट",
      en: "Sudden weakness in face/arm/leg or sudden slurred speech",
      ta: "திடீரென முகம், கை அல்லது காலில் பலவீனம் / பேச்சு குளறுதல்",
    },
    description: {
      mr: "मेंदूच्या रक्तवाहिन्यांचा विकार - तातडीने रुग्णालयात हलवा",
      hi: "न्यूरोलॉजिकल आपातकाल - तत्काल अस्पताल रेफर करें",
      en: "Acute neurological focal deficit requiring urgent neurovascular workup",
      ta: "நரம்பியல் அவசர நிலை - உடனடி மருத்துவ பரிசோதனை தேவை",
    },
  },
  {
    id: "history_of_fainting_or_syncope",
    isDangerSign: true,
    category: "adult_emergency",
    labels: {
      mr: "अचानक चक्कर येऊन पडणे किंवा क्षणिक अंधारी/बेशुद्धावस्था",
      hi: "अचानक चक्कर खाकर गिरना या बेहोश होना (Syncope)",
      en: "Sudden fainting or blackout (Syncope)",
      ta: "திடீர் மயக்கம் அல்லது நினைவிழப்பு",
    },
    description: {
      mr: "हृदयाचे ठोके अनियमित असणे किंवा तीव्र रक्तदाब घटल्याचे लक्षण",
      hi: "हार्ट या गंभीर रक्तचाप समस्या का संकेत - तुरंत जांच कराएं",
      en: "Sign of cardiac arrhythmia, severe hypotension, or neurovascular event",
      ta: "இதய துடிப்பு ஒழுங்கின்மை அல்லது தீவிர இரத்த அழுத்த குறைவின் அறிகுறி",
    },
  },
  {
    id: "post_seizure_stage",
    isDangerSign: false,
    category: "adult_emergency",
    labels: {
      mr: "झटका येऊन गेल्यानंतरची अवस्था (गोंधळ, गुंगी किंवा सावरण्याची वेळ)",
      hi: "दौरे के बाद की अवस्था (भ्रम, अत्यधिक नींद या धीरे-धीरे होश में आना)",
      en: "Post-seizure stage (Confused, sleepy, or recovering after a fit)",
      ta: "வலிப்புக்கு பிந்தைய நிலை (மயக்கம், தூக்க கலக்கம் அல்லது மெதுவாக மீளுதல்)",
    },
    description: {
      mr: "झटका आल्यानंतर रुग्णावर लक्ष ठेवणे आणि डॉक्टरांकडून तपासणी आवश्यक",
      hi: "दौरे के बाद मरीज की निगरानी और डॉक्टर को दिखाना आवश्यक",
      en: "Post-ictal state requiring medical observation and neurological evaluation",
      ta: "வலிப்பு நின்ற பின் மருத்துவ கண்காணிப்பு அவசியம்",
    },
  },
  {
    id: "snake_bite",
    isDangerSign: true,
    category: "adult_emergency",
    labels: {
      mr: "सर्पदंश (साप चावल्याच्या खुणा, सूज, तीव्र वेदना किंवा विषबाधा लक्षणे)",
      hi: "सांप का काटना (दांत के निशान, सूजन, दर्द या सुन्न होना)",
      en: "Snake bite (Fang marks, local swelling, bleeding or neurotoxicity)",
      ta: "பாம்பு கடி (பல் தடம், வீக்கம், இரத்தப்போக்கு அல்லது மயக்கம்)",
    },
    description: {
      mr: "तातडीने १०८ ला फोन करा; रुग्णाला न हलवता अँटी-व्हेनम (ASV) उपलब्ध असलेल्या रुग्णालयात न्या",
      hi: "आपातकालीन स्थिति - मरीज को शांत रखें, हिलाएं नहीं और तुरंत एंटी-वेनम वाले अस्पताल ले जाएं",
      en: "Medical emergency - keep patient calm and immobilized, rush to ASV-equipped hospital",
      ta: "உடனடி அவசர நிலை - நோயாளியை அசையாமல் வைத்து ஆண்டி-வெனம் உள்ள மருத்துவமனைக்கு கொண்டு செல்லவும்",
    },
  },
  {
    id: "scorpion_bite",
    isDangerSign: true,
    category: "adult_emergency",
    labels: {
      mr: "विंचू चावणे (असह्य ठसठसणारी वेदना, घाम येणे, उलट्या)",
      hi: "बिच्छू का काटना (अत्यधिक तेज दर्द, पसीना, उल्टी)",
      en: "Scorpion bite (Severe agonizing local pain, sweating, vomiting)",
      ta: "தேள் கடி (கடுமையான வலி, அதிக வியர்வை, வாந்தி)",
    },
    description: {
      mr: "फुप्फुसात सूज येण्याचा व गुंतागुंतीचा धोका - तातडीने रुग्णालयात हलवा",
      hi: "तीव्र दर्द और फेफड़ों में पानी भरने का खतरा - तुरंत अस्पताल भेजें",
      en: "High risk of autonomic storm and acute pulmonary edema - transfer immediately",
      ta: "நுரையீரல் வீக்கம் மற்றும் கடுமையான இதய பாதிப்பு ஆபத்து - உடனடி சிகிச்சை தேவை",
    },
  },
  {
    id: "suspected_poisoning_with_unstable_vitals",
    isDangerSign: true,
    category: "adult_emergency",
    labels: {
      mr: "विषबाधा किंवा कीटकनाशक पोटात जाणे आणि प्रकृती गंभीर असणे",
      hi: "जहर या कीटनाशक का सेवन और गंभीर अस्वस्थ स्थिति",
      en: "Suspected poisoning or chemical ingestion with unstable vitals",
      ta: "விஷம் அல்லது பூச்சிக்கொல்லி உட்கொண்ட நிலை மற்றும் தீவிர உடல்நலக்குறைவு",
    },
    description: {
      mr: "तातडीने १०८ रुग्णवाहिका बोलावून अतिदक्षता विभागात हलवा",
      hi: "अत्यंत गंभीर आपातकाल - 108 बुलाकर तुरंत विष-रोधी उपचार केंद्र भेजें",
      en: "Critical toxicological emergency requiring resuscitation, gastric lavage, and antidotes",
      ta: "உடனடி அவசர தீவிர சிகிச்சை மற்றும் மாற்று மருந்து தேவைப்படும் நிலை",
    },
  },
  {
    id: "drug_overdose_or_poisoning_with_stable_vitals",
    isDangerSign: false,
    category: "adult_emergency",
    labels: {
      mr: "औषधांचा अतिडोस किंवा रसायन पोटात जाणे (सध्या प्रकृती स्थिर)",
      hi: "दवा की अधिक खुराक या रसायन निगलना (वर्तमान में स्थिर)",
      en: "Suspected drug overdose or chemical ingestion with stable vitals",
      ta: "அளவுக்கு அதிகமான மருந்து அல்லது ரசாயனம் உட்கொண்ட நிலை (தற்போது நிலையானது)",
    },
    description: {
      mr: "रुग्णालयात दाखल करून डॉक्टरांच्या देखरेखीखाली ठेवणे आवश्यक",
      hi: "अस्पताल में निगरानी और जांच आवश्यक",
      en: "Requires immediate hospital observation and toxicological assessment",
      ta: "மருத்துவமனை கண்காணிப்பு மற்றும் நச்சு நீக்க சிகிச்சை தேவை",
    },
  },
  {
    id: "hanging_or_near_drowning_or_electrocution_or_heat_stroke",
    isDangerSign: true,
    category: "adult_emergency",
    labels: {
      mr: "गळफास, पाण्यात बुडणे, विजेचा जोरदार धक्का किंवा तीव्र उष्माघात",
      hi: "फांसी, पानी में डूबना, गंभीर बिजली का झटका या लू लगना (Heat stroke)",
      en: "Hanging, near-drowning, severe electrocution, or heat stroke",
      ta: "தூக்குப்போடுதல், நீரில் மூழ்குதல், மின்சாரம் தாக்குதல் அல்லது தீவிர வெப்ப பக்கவாதம்",
    },
    description: {
      mr: "जीवघेणी आणीबाणी - तातडीने १०८ बोलावून पुनरुज्जीवन उपचार करा",
      hi: "प्राणघातक आपातकाल - तुरंत सीपीआर/ऑक्सीजन और 108 एम्बुलेंस सहायता",
      en: "Life-threatening environmental emergency requiring immediate CPR and resuscitation",
      ta: "உயிருக்கு ஆபத்தான நிலை - உடனடி முதலுதவி மற்றும் தீவிர சிகிச்சை தேவை",
    },
  },
  {
    id: "burn_present",
    isDangerSign: false,
    category: "adult_emergency",
    labels: {
      mr: "भाजलेली जखम किंवा भाजल्याची दुखापत",
      hi: "जलने की चोट या घाव",
      en: "Burn injury present",
      ta: "தீக்காயம் அல்லது சுட்ட காயம்",
    },
    description: {
      mr: "भाजलेली जागा स्वच्छ कापडाने झाका आणि योग्य उपचारासाठी रुग्णालयात पाठवा",
      hi: "जलने की चोट - साफ कपड़े से ढकें, प्राथमिक उपचार और अस्पताल में रेफर करें",
      en: "Thermal, chemical or electrical burn requiring dressing, fluid resuscitation and pain relief",
      ta: "தீக்காயத்திற்கு முறையான முதலுதவி மற்றும் மருத்துவமனை சிகிச்சை",
    },
  },
  {
    id: "stab_or_penetrating_injury",
    isDangerSign: true,
    category: "adult_emergency",
    labels: {
      mr: "सुल्या, सुरा किंवा टोकदार वस्तूने खोलवर झालेली जखम",
      hi: "चाकू, धारदार हथियार या नुकीली चीज से गहरा घाव (Stab injury)",
      en: "Stab wound, penetrating injury, or impaled object",
      ta: "கத்தி குத்து காயம் அல்லது ஊடுருவிய ஆழமான காயம்",
    },
    description: {
      mr: "आतील अवयवांना दुखापत आणि रक्तस्रावाचा धोका - शस्त्रक्रिया केंद्रात हलवा",
      hi: "भीतरी अंगों में चोट और रक्तस्राव का बड़ा खतरा - तुरंत सर्जरी केंद्र भेजें",
      en: "High risk of internal organ injury and severe internal bleeding",
      ta: "உள் உறுப்புகள் சேதம் மற்றும் தீவிர உள் இரத்தப்போக்கு ஆபத்து",
    },
  },
  {
    id: "limb_injury_with_absent_distal_pulse",
    isDangerSign: true,
    category: "adult_emergency",
    labels: {
      mr: "हात-पायाला दुखापत ज्यामध्ये नाडी लागत नाही किंवा हात-पाय थंड पडले आहेत",
      hi: "हाथ-पैर की चोट जिसमें नाड़ी न मिले या अंग ठंडा पड़ जाए",
      en: "Limb trauma/fracture with cold extremity or absent pulse",
      ta: "கை காலில் காயம் ஏற்பட்டு நாடித்துடிப்பு இல்லாத அல்லது குளிர்ந்துபோன நிலை",
    },
    description: {
      mr: "रक्तवाहिन्या तुटल्याचे लक्षण - हात/पाय वाचवण्यासाठी तातडीने हलवा",
      hi: "रक्तवाहिका रुकने का संकेत - अंग बचाने के लिए तुरंत बड़े अस्पताल रेफर करें",
      en: "Acute arterial compromise / limb ischemia requiring urgent vascular restoration within hours",
      ta: "இரத்த ஓட்டம் தடைபட்ட நிலை - கை கால் செயல் இழப்பை தடுக்க உடனடி அறுவை சிகிச்சை",
    },
  },
  {
    id: "two_or_more_long_bone_fractures",
    isDangerSign: true,
    category: "adult_emergency",
    labels: {
      mr: "दोन किंवा अधिक मोठ्या हाडांचे फ्रॅक्चर (मांडी, पायाचे किंवा हाताचे हाड)",
      hi: "दो या अधिक बड़ी हड्डियों का टूटना (जांघ, पैर या बांह)",
      en: "Two or more long-bone fractures (Thigh, leg, or arm bones)",
      ta: "இரண்டு அல்லது அதற்கு மேற்பட்ட நீண்ட எலும்பு முறிவுகள் (தொடை, கால் அல்லது கை எலும்புகள்)",
    },
    description: {
      mr: "प्रचंड रक्तस्राव आणि शॉकचा धोका - आधार पट्टी लावून तातडीने हलवा",
      hi: "भारी रक्तस्राव और शॉक का गंभीर जोखिम - तुरंत स्प्लिंट लगाकर रेफर करें",
      en: "Major orthopedic trauma carrying massive blood loss and hypovolemic shock risk",
      ta: "அதிக இரத்த இழப்பு மற்றும் அதிர்ச்சி ஆபத்து - உடனடி அவசர சிகிச்சை",
    },
  },
  {
    id: "isolated_long_bone_fracture",
    isDangerSign: false,
    category: "adult_emergency",
    labels: {
      mr: "एका मोठ्या हाडाचे फ्रॅक्चर (बंदिस्त फ्रॅक्चर)",
      hi: "एक बड़ी हड्डी में फ्रैक्चर (बंद फ्रैक्चर)",
      en: "Single bone fracture / Closed long-bone fracture",
      ta: "ஒற்றை எலும்பு முறிவு (தொடை, கை அல்லது கால்)",
    },
    description: {
      mr: "आधार पट्टी (स्प्लिंट) लावा आणि एक्स-रे व प्लास्टरसाठी रुग्णालयात पाठवा",
      hi: "स्प्लिंट से सहारा दें, दर्द की दवा दें और एक्स-रे व प्लास्टर हेतु रेफर करें",
      en: "Immobilize with splint, relieve pain, and refer for radiological alignment and cast",
      ta: "எலும்பு அசையாமல் கட்டுப்போட்டு எக்ஸ்-ரே மற்றும் மாவுக்கட்டுக்கு பரிந்துரைக்கவும்",
    },
  },
  {
    id: "fracture_of_hand_or_feet",
    isDangerSign: false,
    category: "adult_emergency",
    labels: {
      mr: "हात, पाय, बोटे किंवा तळपायाच्या हाडाचे फ्रॅक्चर",
      hi: "हाथ, पैर, अंगुलियों या पंजों की हड्डी में फ्रैक्चर का संशय",
      en: "Suspected fracture of fingers, hand, toes, or foot",
      ta: "கை விரல்கள், கால் விரல்கள் அல்லது பாதத்தில் எலும்பு முறிவு",
    },
    description: {
      mr: "आधार द्या आणि एक्स-रे तपासणीसाठी रुग्णालयात पाठवा",
      hi: "स्प्लिंट लगाएं और एक्स-रे हेतु रेफर करें",
      en: "Small bone injury - immobilize and refer to secondary facility for X-ray",
      ta: "முதலுதவி அளித்து எக்ஸ்-ரே பரிசோதனைக்கு அனுப்பவும்",
    },
  },
  {
    id: "minor_head_injury",
    isDangerSign: false,
    category: "adult_emergency",
    labels: {
      mr: "डोक्याला किरकोळ मार (शुद्धीत, उलट्या नाहीत)",
      hi: "सिर में हल्की चोट (होश में, कोई उल्टी नहीं)",
      en: "Minor head injury (Conscious, no vomiting, no neurological deficits)",
      ta: "தலையில் லேசான காயம் (சுயநினைவுடன், வாந்தி இன்றி)",
    },
    description: {
      mr: "२४ तास उलट्या, गुंगी किंवा झटके या लक्षणांवर बारीक लक्ष ठेवा",
      hi: "24 घंटे तक उल्टी, सुस्ती या बेहोशी के लक्षणों पर नजर रखें",
      en: "Monitor for delayed neurological signs (vomiting, drowsiness, seizure) over 24 hours",
      ta: "24 மணி நேரம் வாந்தி அல்லது மயக்க அறிகுறிகள் உள்ளதா என கண்காணிக்கவும்",
    },
  },
  {
    id: "multiple_injuries",
    isDangerSign: true,
    category: "adult_emergency",
    labels: {
      mr: "शरीरावर अनेक ठिकाणी झालेली गंभीर दुखापत (पॉलीट्रामा)",
      hi: "शरीर में कई जगह गंभीर चोटें (Multiple injuries)",
      en: "Multiple trauma / Multiple injuries across body",
      ta: "உடலில் பல இடங்களில் ஏற்பட்ட கடுமையான காயங்கள்",
    },
    description: {
      mr: "तातडीने १०८ रुग्णवाहिका बोलावून ट्रॉमा केअर सेंटरमध्ये दाखल करा",
      hi: "गंभीर दुर्घटना - तुरंत 108 बुलाकर ट्रॉमा सेंटर भेजें",
      en: "Polytrauma requiring rapid trauma assessment, stabilization and transfer",
      ta: "தீவிர விபத்து காயம் - உடனடி தீவிர சிகிச்சை மையம் பரிந்துரை",
    },
  },
  {
    id: "subcutaneous_crackles_or_seatbelt_mark",
    isDangerSign: true,
    category: "adult_emergency",
    labels: {
      mr: "त्वचेखाली हवेचा फुगा/खरखर जाणवणे किंवा छाती/पोटावर सीटबेल्टचा खोल वळ",
      hi: "त्वचा के नीचे हवा महसूस होना (सलबलाहट) या छाती/पेट पर सीटबेल्ट का गहरा निशान",
      en: "Subcutaneous crackles (Air under skin) or seatbelt/steering wheel bruise mark",
      ta: "தோலின் அடியில் காற்று குமிழ்கள் அல்லது மார்பில் சீட்பெல்ட்/ஸ்டீயரிங் அழுத்தக் காயம்",
    },
    description: {
      mr: "फुप्फुसाला छिद्र किंवा अंतर्गत अवयवांना गंभीर इजा झाल्याचे लक्षण",
      hi: "फेफड़े फटने या अंदरूनी गंभीर चोट का संकेत - तुरंत रेफर करें",
      en: "Sign of pneumothorax, bronchial rupture, or severe blunt abdominal trauma",
      ta: "நுரையீரல் சேதம் அல்லது கடுமையான உள் உறுப்பு காயம்",
    },
  },
  {
    id: "suspected_neck_injury",
    isDangerSign: true,
    category: "adult_emergency",
    labels: {
      mr: "अपघात किंवा पडल्यामुळे मानेच्या मणक्याला दुखापत झाल्याचा संशय",
      hi: "गर्दन या रीढ़ की हड्डी के ऊपरी भाग में चोट का संशय",
      en: "Suspected neck or cervical spine injury after fall/crash",
      ta: "விபத்து அல்லது கீழே விழுந்ததால் கழுத்து எலும்பில் காயம்",
    },
    description: {
      mr: "मान अजिबात वाकवू नका, मानेला आधार द्या आणि न हलवता रुग्णालयात न्या",
      hi: "गर्दन को बिल्कुल न मोड़ें, कॉलर लगाएं और सीधे लिटाकर अस्पताल भेजें",
      en: "Immobilize cervical spine immediately, do not bend neck, transport on rigid spine board",
      ta: "கழுத்தை அசைக்காமல் நேராக வைத்து உடனடி மருத்துவமனைக்கு கொண்டு செல்லவும்",
    },
  },
  {
    id: "suspected_spine_injury",
    isDangerSign: true,
    category: "adult_emergency",
    labels: {
      mr: "पाठीच्या मणक्याला दुखापत आणि पायात बधिरता किंवा हालचाल बंद होणे",
      hi: "पीठ/रीढ़ की हड्डी में चोट और पैरों में सुन्नपन या कमजोरी",
      en: "Suspected back/spine injury with numbness or weakness in legs",
      ta: "முதுகெலும்பு காயம் மற்றும் கால்களில் மரத்துப்போதல் அல்லது பலவீனம்",
    },
    description: {
      mr: "मणक्याची गंभीर दुखापत - रुग्णाला सरळ सपाट पृष्ठभागावर झोपवून हलवा",
      hi: "रीढ़ की हड्डी की गंभीर चोट - मरीज को सीधा लिटाकर ले जाएं",
      en: "Spinal cord injury risk - log-roll only, transport flat on hard surface",
      ta: "முதுகெலும்பு பாதிப்பு - உடலை வளைக்காமல் படுக்க வைத்து கொண்டு செல்லவும்",
    },
  },
  {
    id: "ongoing_bleeding_vomitus_cough_urine_or_nose",
    isDangerSign: true,
    category: "adult_emergency",
    labels: {
      mr: "उलटीतून, खोकल्यातून, लघवीतून, शौचातून रक्त पडणे किंवा नाकातून सतत रक्त वाहणे",
      hi: "उल्टी में खून, खांसी में खून, पेशाब/मल में खून या लगातार नकसीर फूटना",
      en: "Ongoing bleeding in vomitus, cough, urine, stools, or persistent nosebleed",
      ta: "வாந்தியில் இரத்தம், இருமலில் இரத்தம், சிறுநீரில் இரத்தம் அல்லது மூக்கில் தீவிர இரத்தப்போக்கு",
    },
    description: {
      mr: "गंभीर अंतर्गत रक्तस्राव - तातडीने १०८ रुग्णवाहिका बोलावून रुग्णालयात दाखल करा",
      hi: "गंभीर आंतरिक रक्तस्राव - तत्काल 108 बुलाकर अस्पताल ले जाएं",
      en: "Active severe internal/mucosal hemorrhage requiring urgent resuscitation and blood matching",
      ta: "தீவிர உள் இரத்தப்போக்கு - உடனடி தீவிர சிகிச்சை மற்றும் இரத்த பரிசோதனை தேவை",
    },
  },
  {
    id: "suspected_sexual_assault",
    isDangerSign: true,
    category: "adult_emergency",
    labels: {
      mr: "लैंगिक अत्याचार / हिंसेची शिकार झालेली व्यक्ती (तातडीने वैद्यकीय मदत)",
      hi: "यौन हिंसा / हमले का शिकार व्यक्ति (तत्काल चिकित्सा और सहायता)",
      en: "Survivor of suspected sexual assault / Gender-based violence",
      ta: "பாலியல் வன்கொடுமையால் பாதிக்கப்பட்டவர் (உடனடி மருத்துவ உதவி)",
    },
    description: {
      mr: "तातडीने गोपनीय वैद्यकीय तपासणी, आपत्कालीन गर्भनिरोधक व संसर्ग प्रतिबंधक उपचार",
      hi: "गोपनीय आपातकालीन चिकित्सा, गर्भनिरोधक और संक्रमण रोकथाम आवश्यक",
      en: "Requires confidential medical exam, emergency contraception, STI prophylaxis, and support",
      ta: "ரகசிய மருத்துவ பரிசோதனை, அவசர கருத்தடை மற்றும் தொற்று தடுப்பு சிகிச்சை",
    },
  },
  {
    id: "fresh_scratches_or_wounds",
    isDangerSign: false,
    category: "adult_emergency",
    labels: {
      mr: "ताजी खरचटलेली जखम, कातडी सोलणे किंवा किरकोळ कापल्याची जखम",
      hi: "ताजा खरोंच, छिलना या छोटा घाव",
      en: "Fresh scratches, superficial abrasions, or minor cuts",
      ta: "புதிய கீறல்கள், சிராய்ப்புகள் அல்லது லேசான வெட்டுக்காயம்",
    },
    description: {
      mr: "जखम स्वच्छ पाण्याने धुवा, जंतुनाशक मलम व पट्टी लावा आणि धनुर्वात (TT) लस तपासा",
      hi: "घाव को साफ पानी व एंटीसेप्टिक से धोएं, पट्टी बांधें और टिटनेस का टीका जांचें",
      en: "Clean with antiseptic and clean water, apply sterile dressing, check Tetanus Toxoid status",
      ta: "காயத்தை சுத்தமாக கழுவி கட்டுப்போடவும் மற்றும் டெட்டனஸ் ஊசி நிலையை சரிபார்க்கவும்",
    },
  },
  {
    id: "painful_swelling_or_wound",
    isDangerSign: false,
    category: "adult_emergency",
    labels: {
      mr: "दुखणारी सूज, गळू किंवा पू भरलेली जखम (सेल्युलायटिस)",
      hi: "दर्दनाक सूजन, फोड़ा या पका हुआ घाव (Abscess / Cellulitis)",
      en: "Painful infected swelling, abscess, or inflamed wound",
      ta: "கடுமையான வலி தரும் வீக்கம், சீழ்க்கட்டி அல்லது புண்",
    },
    description: {
      mr: "त्वचेचा संसर्ग किंवा गळू - प्राथमिक आरोग्य केंद्रात दाखवून उपचार घ्या",
      hi: "त्वचा संक्रमण या फोड़ा - स्वास्थ्य केंद्र में दिखाएं",
      en: "Localized skin/soft tissue infection - evaluate for drainage or antibiotics",
      ta: "தோல் தொற்று அல்லது சீழ்க்கட்டி - மருத்துவ சிகிச்சை தேவை",
    },
  },
  {
    id: "body_ache",
    isDangerSign: false,
    category: "adult_emergency",
    labels: {
      mr: "अंगदुखी / सर्व अंगात वेदना होणे",
      hi: "पूरे शरीर में दर्द या बदन टूटना",
      en: "Generalized body ache / Musculoskeletal soreness",
      ta: "முழு உடல் வலி / தசை அசதி",
    },
    description: {
      mr: "अंगदुखी - विश्रांती घ्या आणि भरपूर पाणी प्या",
      hi: "सामान्य बदन दर्द - आराम और पर्याप्त पानी लें",
      en: "Symptom of viral illness, physical exhaustion, or systemic infection",
      ta: "உடல் வலி - ஓய்வு மற்றும் திரவ உணவுகள் தேவை",
    },
  },
  {
    id: "body_pain_weakness",
    isDangerSign: false,
    category: "adult_emergency",
    labels: {
      mr: "अंगदुखी आणि तीव्र थकवा / गळून गेल्यासारखे वाटणे",
      hi: "शरीर में दर्द के साथ अत्यधिक कमजोरी और थकान",
      en: "Generalized body pain with pronounced weakness / malaise",
      ta: "உடல் வலியுடன் கூடிய தீவிர சோர்வு மற்றும் பலவீனம்",
    },
    description: {
      mr: "प्रचंड थकवा आणि अशक्तपणा - आरोग्य केंद्रात तपासणी आवश्यक",
      hi: "अत्यधिक कमजोरी - स्वास्थ्य केंद्र में जांच कराएं",
      en: "Debilitating weakness requiring vital sign assessment and clinical workup",
      ta: "கடுமையான பலவீனம் - மருத்துவ பரிசோதனை தேவை",
    },
  },
  {
    id: "significant_weight_loss",
    isDangerSign: false,
    category: "adult_emergency",
    labels: {
      mr: "अचानक वजन खूप कमी होणे",
      hi: "अचानक वजन कम होना",
      en: "Significant / Unexplained Weight Loss",
      ta: "குறிப்பிடத்தக்க / விவரிக்க முடியாத எடை இழப்பு",
    },
    description: {
      mr: "विनाकारण वजन घटणे - टीबी, मधुमेह किंवा जुनाट आजारांची तपासणी करा",
      hi: "बिना कारण वजन घटना - टीबी, मधुमेह या अन्य पुरानी बीमारियों की जांच कराएं",
      en: "Unintentional weight loss - screen for Tuberculosis, Diabetes, or chronic illnesses",
      ta: "எடை குறைதல் - காசநோய் அல்லது நீரிழிவு பரிசோதனை அவசியம்",
    },
  },
  {
    id: "painful_urination",
    isDangerSign: false,
    category: "adult_emergency",
    labels: {
      mr: "लघवी करताना आग होणे किंवा दुखणे",
      hi: "पेशाब में जलन या दर्द होना (Dysuria)",
      en: "Painful or burning urination (Dysuria)",
      ta: "சிறுநீர் கழிக்கும் போது எரிச்சல் அல்லது வலி",
    },
    description: {
      mr: "मूत्रमार्गाचा जंतुसंसर्ग (UTI) - भरपूर पाणी प्या आणि लघवीची तपासणी करा",
      hi: "मूत्र संक्रमण (UTI) का संकेत - खूब पानी पिएं और पेशाब की जांच कराएं",
      en: "Sign of urinary tract infection (UTI) - encourage water intake and refer for urine test",
      ta: "சிறுநீரக பாதை தொற்று - அதிக தண்ணீர் குடிக்கவும் மற்றும் பரிசோதனை செய்யவும்",
    },
  },
  {
    id: "pallor_or_pale_skin_or_conjunctiva",
    isDangerSign: false,
    category: "adult_emergency",
    labels: {
      mr: "त्वचा, तळहात किंवा डोळे पांढरे पडणे (अशक्तपणा/अ‍ॅनिमिया)",
      hi: "त्वचा, हथेलियों या आंखों में पीलापन (एनीमिया)",
      en: "Pale Skin, Palms or Eyes (Pallor/Anaemia)",
      ta: "வெளிறிய தோல், உள்ளங்கை அல்லது கண்கள் (ரத்த சோகை)",
    },
    description: {
      mr: "रक्ताची कमतरता (अ‍ॅनिमिया) - हिमोग्लोबिन तपासा आणि लोहाच्या (IFA) गोळ्या द्या",
      hi: "खून की कमी (एनीमिया) का लक्षण - हीमोग्लोबिन जांच और आयरन की गोली दें",
      en: "Clinical sign of anaemia - test haemoglobin level and provide IFA supplementation",
      ta: "இரத்த சோகை அறிகுறி - ஹீமோகுளோபின் பரிசோதனை மற்றும் இரும்புச்சத்து மாத்திரைகள் தேவை",
    },
  },
  {
    id: "pallor_with_breathlessness_or_foot_swelling",
    isDangerSign: true,
    category: "adult_emergency",
    labels: {
      mr: "तीव्र पांढरेपणा (रक्तक्षय) आणि सोबत धाप लागणे किंवा पायांवर सूज असणे",
      hi: "अत्यधिक पीलापन और साथ में सांस फूलना या पैरों में सूजन (गंभीर एनीमिया)",
      en: "Severe pallor with breathlessness or swelling in feet (Severe anaemia in heart failure)",
      ta: "கடுமையான வெளிறிய தோலுடன் மூச்சுத்திணறல் அல்லது பாத வீக்கம்",
    },
    description: {
      mr: "अतिगंभीर अ‍ॅनिमिया आणि हृदयावर ताण - तातडीने रक्त भरण्यासाठी रुग्णालयात पाठवा",
      hi: "गंभीर एनीमिया और हार्ट फेलियर का जोखिम - तुरंत रक्त चढ़ाने हेतु अस्पताल रेफर करें",
      en: "Decompensated severe anaemia / high-output cardiac failure requiring urgent blood transfusion",
      ta: "தீவிர இரத்த சோகை மற்றும் இதய செயலிழப்பு ஆபத்து - உடனடி இரத்தம் செலுத்துதல் தேவை",
    },
  },
  {
    id: "skin_rash",
    isDangerSign: false,
    category: "adult_emergency",
    labels: {
      mr: "त्वचेवर लाल पुरळ, पुरळ उठणे किंवा खाज येणे",
      hi: "त्वचा पर लाल चकत्ते या खुजली वाले दाने",
      en: "Skin rash / Itchy red spots",
      ta: "தோல் அரிப்பு / சிவப்பு தடிப்புகள்",
    },
    description: {
      mr: "त्वचेचा संसर्ग किंवा अ‍ॅलर्जी - प्राथमिक आरोग्य केंद्रात दाखवा",
      hi: "त्वचा पर दाने या एलर्जी - स्वास्थ्य केंद्र में दिखाएं",
      en: "Dermatological eruption - differentiate allergic, viral exanthem, or fungal infection",
      ta: "தோல் அலர்ஜி அல்லது வைரஸ் தடிப்பு",
    },
  },
  {
    id: "swelling_face_or_hands",
    isDangerSign: false,
    category: "adult_emergency",
    labels: {
      mr: "तोंड, डोळे किंवा हाता-पायांवर सूज",
      hi: "चेहरे, आंखों या हाथ-पैरों पर सूजन",
      en: "Swelling in face, eyes or feet (Edema)",
      ta: "முகம், கண்கள் அல்லது கை கால் வீக்கம்",
    },
    description: {
      mr: "डोळ्यांभोवती किंवा चेहऱ्यावर सूज जाणवणे",
      hi: "आंखों या चेहरे पर असामान्य सूजन",
      en: "Noticeable edema around eyes or face",
      ta: "கண்களைச் சுற்றி அல்லது முகத்தில் வீக்கம்",
    },
  },
  {
    id: "fever_in_chemo_or_hiv_or_diabetic_patient",
    isDangerSign: false,
    category: "adult_emergency",
    labels: {
      mr: "मधुमेह (डायबिटीज / Sugar) आजारासोबत अस्वस्थता",
      hi: "मधुमेह (शुगर / Diabetes) के साथ शारीरिक परेशानी",
      en: "Diabetes / High-risk condition with active illness",
      ta: "நீரிழிவு நோய் (சுகர்) பாதிப்புடன் உடல் உபாதை",
    },
    description: {
      mr: "मधुमेहाच्या रुग्णामध्ये वाढलेली गुंतागुंत",
      hi: "शुगर के मरीज में जटिलता",
      en: "Underlying diabetes requiring clinical review",
      ta: "நீரிழிவு நோயாளிக்கு மருத்துவ பரிசோதனை தேவை",
    },
  },
  {
    id: "fever_with_headache_or_chest_pain_or_jaundice",
    isDangerSign: false,
    category: "adult_emergency",
    labels: {
      mr: "डोळे पिवळे पडणे / कावीळ लक्षणे (Yellow Eyes / Jaundice)",
      hi: "आंखें पीली होना / पीलिया के लक्षण",
      en: "Yellow eyes / Jaundice with fever or malaise",
      ta: "கண்கள் மஞ்சள் நிறமாதல் / மஞ்சள் காமாலை",
    },
    description: {
      mr: "यकृताचा संसर्ग किंवा कावीळ",
      hi: "पीलिया या लिवर संक्रमण",
      en: "Acute hepatitis or hepatic involvement",
      ta: "கல்லீரல் தொற்று அல்லது மஞ்சள் காமாலை",
    },
  },
  {
    id: "severe_allergic_reaction_lip_throat_swelling",
    isDangerSign: true,
    category: "adult_emergency",
    labels: {
      mr: "अ‍ॅलर्जीची तीव्र प्रतिक्रिया - ओठ, जीभ किंवा घसा सुजणे व धाप लागणे",
      hi: "गंभीर एलर्जी - होंठ, जीभ या गले में सूजन और सांस फूलना (एनाफिलेक्सिस)",
      en: "Severe allergic reaction with lip/tongue/throat swelling (Anaphylaxis)",
      ta: "கடுமையான ஒவ்வாமை - உதடு, நாக்கு அல்லது தொண்டை வீக்கம்",
    },
    description: {
      mr: "अ‍ॅनाफिलेक्सिसचा मोठा धोका - तातडीने १०८ बोलावून अ‍ॅड्रेनालिन उपचारासाठी रुग्णालयात हलवा",
      hi: "एनाफिलेक्सिस आपातकाल - तुरंत 108 बुलाएं और एड्रेनालिन उपचार हेतु अस्पताल ले जाएं",
      en: "Life-threatening anaphylaxis requiring immediate intramuscular epinephrine and airway support",
      ta: "உயிருக்கு ஆபத்தான ஒவ்வாமை அதிர்ச்சி - உடனடி அவசர சிகிச்சை தேவை",
    },
  },
  {
    id: "bleeding_from_vagina_any_amount",
    isDangerSign: true,
    category: "maternal",
    applicableSex: "female",
    onlyPregnantOrPostpartum: true,
    labels: {
      mr: "गरोदरपणात योनीतून रक्तस्त्राव",
      hi: "गर्भावस्था में योनि से रक्तस्राव",
      en: "Vaginal bleeding during pregnancy",
      ta: "கர்ப்ப காலத்தில் யோனி இரத்தப்போக்கு",
    },
    description: {
      mr: "तातडीने उपजिल्हा/जिल्हा रुग्णालयात हलवा",
      hi: "तुरंत अस्पताल रेफर करें",
      en: "Obstetric emergency requiring immediate surgical facility",
      ta: "உடனடி அவசர மருத்துவமனை பரிந்துரை",
    },
  },
  {
    id: "bleeding_pad_soaked_lt_5_min",
    isDangerSign: true,
    category: "maternal",
    applicableSex: "female",
    onlyPregnantOrPostpartum: true,
    labels: {
      mr: "५ मिनिटांपेक्षा कमी वेळेत पॅड पूर्ण भिजणे (अतिरक्तस्राव)",
      hi: "5 मिनट से भी कम समय में पैड पूरी तरह भीग जाना (अत्यधिक रक्तस्राव)",
      en: "Severe bleeding soaking a pad in less than 5 minutes",
      ta: "5 நிமிடத்திற்குள் பேட் நனையும் அளவுக்கு மிக அதிக இரத்தப்போக்கு",
    },
    description: {
      mr: "तातडीने १०८ रुग्णवाहिका बोलावून रुग्णालयात हलवा",
      hi: "अत्यधिक रक्तस्राव - तत्काल 108 एम्बुलेंस बुलाएं",
      en: "Massive active bleeding requiring immediate emergency transfer",
      ta: "உடனடி அவசர சிகிச்சை தேவைப்படும் கடுமையான இரத்தப்போக்கு",
    },
  },
  {
    id: "heavy_bleeding_postpartum",
    isDangerSign: true,
    category: "maternal",
    applicableSex: "female",
    onlyPregnantOrPostpartum: true,
    labels: {
      mr: "बाळंतपणानंतर अतिरक्तस्राव (PPH)",
      hi: "प्रसव के बाद अत्यधिक रक्तस्राव (PPH)",
      en: "Heavy Bleeding After Delivery (PPH)",
      ta: "பிரசவத்திற்கு பின் அதிக இரத்தப்போக்கு (PPH)",
    },
    description: {
      mr: "बाळंतपणानंतर अतिरक्तस्त्राव - तातडीने १०८ ला फोन करा",
      hi: "प्रसवोत्तर रक्तस्राव - तत्काल 108 बुलाकर अस्पताल ले जाएं",
      en: "Postpartum hemorrhage (PPH) - leading cause of maternal mortality",
      ta: "பிரசவத்திற்கு பிந்தைய அதீத இரத்தப்போக்கு - உடனடி தீவிர சிகிச்சை தேவை",
    },
  },
  {
    id: "more_than_5_pads_per_day_or_1_thick_cloth_per_day",
    isDangerSign: false,
    category: "maternal",
    applicableSex: "female",
    onlyPregnantOrPostpartum: true,
    labels: {
      mr: "बाळंतपणानंतर दिवसाला ५ पेक्षा जास्त पॅड किंवा १ जाड कापड पूर्ण भिजणे",
      hi: "प्रसव के बाद प्रतिदिन 5 से अधिक पैड या 1 मोटा कपड़ा भीगना",
      en: "Soaking more than 5 pads per day or 1 thick cloth in postpartum",
      ta: "பிரசவத்திற்கு பின் ஒரு நாளைக்கு 5 பேட்களுக்கு மேல் நனைதல்",
    },
    description: {
      mr: "बाळंतपणानंतरचा असामान्य रक्तस्राव - प्राथमिक आरोग्य केंद्रात दाखवा",
      hi: "प्रसवोत्तर असामान्य रक्तस्राव - स्वास्थ्य केंद्र में जांच कराएं",
      en: "Abnormal postpartum lochial bleeding requiring medical assessment",
      ta: "பிரசவத்திற்கு பிந்தைய வழக்கத்திற்கு மாறான இரத்தப்போக்கு",
    },
  },
  {
    id: "loss_of_foetal_movement_or_severe_abdominal_pain",
    isDangerSign: true,
    category: "maternal",
    applicableSex: "female",
    onlyPregnantOrPostpartum: true,
    labels: {
      mr: "बाळाची हालचाल बंद होणे किंवा पोटात असह्य वेदना",
      hi: "शिशु की हलचल बंद होना या असहनीय पेट दर्द",
      en: "Loss of fetal movements or severe pain",
      ta: "கருவின் அசைவு குறைதல் அல்லது தீவிர வலி",
    },
    description: {
      mr: "गर्भस्थ बालकाचा धोका",
      hi: "गर्भ में बच्चे का न हिलना",
      en: "Compromised fetal well-being",
      ta: "கருவின் பாதுகாப்பிற்கு உடனடி கவனம்",
    },
  },
  {
    id: "decreased_or_absent_foetal_movements",
    isDangerSign: true,
    category: "maternal",
    applicableSex: "female",
    onlyPregnantOrPostpartum: true,
    labels: {
      mr: "गर्भातील बाळाची हालचाल मंदावणे किंवा थांबणे",
      hi: "शिशु की हलचल कम होना या बिल्कुल न होना",
      en: "Decreased or absent fetal movements",
      ta: "கருவின் அசைவு குறைதல் அல்லது முற்றிலும் இல்லாமல் போதல்",
    },
    description: {
      mr: "गर्भस्थ बाळाला धोका असण्याचे लक्षण - तातडीने तपासणी आवश्यक",
      hi: "गर्भस्थ शिशु के लिए खतरे का संकेत - तत्काल जांच आवश्यक",
      en: "Sign of fetal compromise requiring immediate NST/ultrasound evaluation",
      ta: "கருவின் உயிருக்கு ஆபத்தான நிலை - உடனடி மருத்துவ பரிசோதனை",
    },
  },
  {
    id: "severe_headache_with_blurred_vision_or_spots",
    isDangerSign: true,
    category: "maternal",
    applicableSex: "female",
    onlyPregnantOrPostpartum: true,
    labels: {
      mr: "तीव्र डोकेदुखी सोबत अंधारी येणे (Pre-eclampsia)",
      hi: "तेज सिरदर्द के साथ आंखों के आगे धुंधलापन",
      en: "Severe headache with visual disturbance",
      ta: "கடுமையான தலைவலியுடன் பார்வை மங்குதல்",
    },
    description: {
      mr: "गरोदरपणातील अतिरक्तदाब (Pre-eclampsia)",
      hi: "गर्भावस्था में उच्च रक्तचाप",
      en: "Severe pre-eclampsia / hypertensive emergency",
      ta: "கர்ப்பகால உயர் இரத்த அழுத்தம்",
    },
  },
  {
    id: "severe_headache_pregnancy",
    isDangerSign: true,
    category: "maternal",
    applicableSex: "female",
    onlyPregnantOrPostpartum: true,
    labels: {
      mr: "गरोदरपणात तीव्र डोकेदुखी",
      hi: "गर्भावस्था में तेज सिरदर्द",
      en: "Severe Headache (in pregnancy)",
      ta: "கர்ப்ப காலத்தில் கடுமையான தலைவலி",
    },
    description: {
      mr: "गरोदरपणातील तीव्र डोकेदुखी - प्री-एक्लॅम्प्सियाचे धोक्याचे लक्षण",
      hi: "गर्भावस्था में गंभीर सिरदर्द - प्री-एक्लेम्पसिया का चेतावनी संकेत",
      en: "Severe throbbing headache in pregnancy - danger sign of pre-eclampsia",
      ta: "கர்ப்பகால கடுமையான தலைவலி - நச்சுக் குறைபாட்டின் எச்சரிக்கை அறிகுறி",
    },
  },
  {
    id: "blurred_vision_pregnancy",
    isDangerSign: true,
    category: "maternal",
    applicableSex: "female",
    onlyPregnantOrPostpartum: true,
    labels: {
      mr: "गरोदरपणात अंधुक दिसणे",
      hi: "गर्भावस्था में धुंधला दिखना",
      en: "Blurred Vision (in pregnancy)",
      ta: "கர்ப்ப காலத்தில் பார்வை மங்குதல்",
    },
    description: {
      mr: "गरोदरपणातील उच्च रक्तदाब व प्री-एक्लॅम्प्सियाचे धोक्याचे लक्षण",
      hi: "गर्भावस्था में उच्च रक्तचाप और प्री-एक्लेम्पसिया का गंभीर लक्षण",
      en: "Danger sign of severe pre-eclampsia / hypertension in pregnancy",
      ta: "கர்ப்பகால உயர் இரத்த அழுத்தம் மற்றும் தீவிர நச்சுக் குறைபாட்டின் அறிகுறி",
    },
  },
  {
    id: "reduced_urinary_output_with_high_bp",
    isDangerSign: true,
    category: "maternal",
    applicableSex: "female",
    onlyPregnantOrPostpartum: true,
    labels: {
      mr: "गरोदरपणात वाढलेला रक्तदाब आणि लघवीचे प्रमाण खूप कमी होणे",
      hi: "गर्भावस्था में उच्च रक्तचाप के साथ पेशाब कम आना",
      en: "Reduced urinary output with high blood pressure in pregnancy",
      ta: "கர்ப்ப காலத்தில் உயர் இரத்த அழுத்தத்துடன் சிறுநீர் அளவு குறைதல்",
    },
    description: {
      mr: "तीव्र प्री-एक्लॅम्प्सियामध्ये मूत्रपिंडावर ताण आल्याचे लक्षण",
      hi: "गंभीर प्री-एक्लेम्पसिया में किडनी पर असर का संकेत",
      en: "Sign of renal impairment in severe pre-eclampsia / HELLP syndrome",
      ta: "கடுமையான உயர் இரத்த அழுத்தத்தில் சிறுநீரக பாதிப்பின் அறிகுறி",
    },
  },
  {
    id: "eclampsia_seizures",
    isDangerSign: true,
    category: "maternal",
    applicableSex: "female",
    onlyPregnantOrPostpartum: true,
    labels: {
      mr: "गरोदरपणात झटके येणे (एक्लॅम्प्सिया)",
      hi: "गर्भावस्था में दौरे / झटके (एक्लेम्पसिया)",
      en: "Fits / Seizures in Pregnancy (Eclampsia)",
      ta: "கர்ப்ப காலத்தில் வலிப்பு (எக்லாம்ப்சியா)",
    },
    description: {
      mr: "तातडीने मॅग्नेशियम सल्फेट व उपजिल्हा/जिल्हा रुग्णालयात हलवणे आवश्यक",
      hi: "गर्भावस्था में दौरे - तुरंत मैग्नीशियम सल्फेट और उच्च केंद्र रेफरल आवश्यक",
      en: "Obstetric emergency requiring immediate Magnesium Sulfate and referral",
      ta: "உடனடி மெக்னீசியம் சல்பேட் சிகிச்சை மற்றும் உயர் மருத்துவமனை பரிந்துரை",
    },
  },
  {
    id: "baby_lying_sideways_malpresentation",
    isDangerSign: true,
    category: "maternal",
    applicableSex: "female",
    onlyPregnantOrPostpartum: true,
    labels: {
      mr: "गर्भाशयात बाळ आडवे असणे (ट्रान्सव्हर्स लाय)",
      hi: "शिशु की आड़ी स्थिति (ट्रांसवर्स लाई / मैलप्रेजेंटेशन)",
      en: "Baby lying sideways (Transverse lie / Malpresentation)",
      ta: "கருப்பையில் குழந்தை குறுக்காக இருத்தல் (குறுக்கு நிலை)",
    },
    description: {
      mr: "असामान्य स्थिती - तातडीने रुग्णालयात प्रसूती आवश्यक",
      hi: "असामान्य भ्रूण स्थिति - अस्पताल में प्रसव आवश्यक",
      en: "Abnormal fetal presentation requiring hospital delivery",
      ta: "மருத்துவமனையில் உடனடி பிரசவ கண்காணிப்பு தேவை",
    },
  },
  {
    id: "multiple_pregnancy",
    isDangerSign: false,
    category: "maternal",
    applicableSex: "female",
    onlyPregnantOrPostpartum: true,
    labels: {
      mr: "जुळे किंवा एकापेक्षा जास्त गर्भ (मल्टिपल प्रेग्नन्सी)",
      hi: "जुड़वां या एकाधिक गर्भधारण (Multiple pregnancy)",
      en: "Multiple pregnancy (Twins or more confirmed)",
      ta: "இரட்டைக் குழந்தைகள் அல்லது அதற்கு மேற்பட்ட கர்ப்பம்",
    },
    description: {
      mr: "उच्च जोखमीची गरोदरपण - उपजिल्हा रुग्णालयात प्रसूती आवश्यक",
      hi: "उच्च जोखिम वाली गर्भावस्था - अस्पताल में प्रसव की योजना बनाएं",
      en: "High-risk pregnancy requiring planned institutional delivery at FRU",
      ta: "உயர் ஆபத்துள்ள கர்ப்பம் - முறையான மருத்துவமனை பிரசவம் அவசியம்",
    },
  },
  {
    id: "premature_rupture_of_membranes_before_37_weeks",
    isDangerSign: true,
    category: "maternal",
    applicableSex: "female",
    onlyPregnantOrPostpartum: true,
    labels: {
      mr: "३७ आठवडे पूर्ण होण्यापूर्वी पाण्याची पिशवी फुटणे (मुदतपूर्व प्रसूती धोका)",
      hi: "37 सप्ताह से पहले पानी की थैली फटना (प्रीटर्म प्री-लेबर रप्चर)",
      en: "Water breaking before 37 completed weeks of pregnancy (Preterm PROM)",
      ta: "37 வாரங்களுக்கு முன்பே பனிக்குடம் உடைந்து நீர் வெளியேறுதல்",
    },
    description: {
      mr: "मुदतपूर्व पाणी सुटणे - एनआयसीयू सुविधा असलेल्या रुग्णालयात दाखल करा",
      hi: "समय से पहले पानी छूटना - एनआईसीयू युक्त अस्पताल में भर्ती कराएं",
      en: "Preterm premature rupture of membranes requiring immediate NICU-ready referral",
      ta: "குறைபிரசவ நீர் வெளியேற்றம் - உடனடி தீவிர குழந்தைகள் பிரிவு உள்ள மருத்துவமனை பரிந்துரை",
    },
  },
  {
    id: "water_broke_no_labour_within_24h",
    isDangerSign: true,
    category: "maternal",
    applicableSex: "female",
    onlyPregnantOrPostpartum: true,
    labels: {
      mr: "पाणी सुटून २४ तासांनंतरही प्रसूती कळा सुरू न होणे",
      hi: "पानी छूटने के 24 घंटे बाद भी प्रसव पीड़ा शुरू न होना",
      en: "Water breaking with no onset of labour pains within 24 hours",
      ta: "பனிக்குட நீர் கசிந்து 24 மணி நேரத்திற்குள் பிரசவ வலி தொடங்காமல் இருத்தல்",
    },
    description: {
      mr: "जंतुसंसर्ग रोखण्यासाठी आणि प्रसूतीसाठी रुग्णालयात दाखल करणे आवश्यक",
      hi: "संक्रमण रोकने और प्रसव कराने हेतु अस्पताल में भर्ती आवश्यक",
      en: "Requires medical induction of labour and prophylactic antibiotics at hospital",
      ta: "தொற்று தடுப்பு மற்றும் பிரசவத்தை தூண்ட மருத்துவமனையில் சேர்த்தல் அவசியம்",
    },
  },
  {
    id: "ruptured_membranes_more_than_18h",
    isDangerSign: true,
    category: "maternal",
    applicableSex: "female",
    onlyPregnantOrPostpartum: true,
    labels: {
      mr: "पाण्याची पिशवी फुटून १८ तासांपेक्षा जास्त वेळ उलटून जाणे",
      hi: "पानी छूटे 18 घंटे से अधिक हो जाना और प्रसव न होना",
      en: "Water broke more than 18 hours ago without active delivery",
      ta: "பனிக்குடம் உடைந்து 18 மணி நேரத்திற்கும் மேலாகியும் பிரசவம் ஆகாமல் இருத்தல்",
    },
    description: {
      mr: "माता व बालकाला जंतुसंसर्गाचा (सेप्सिस) मोठा धोका - तातडीने रुग्णालयात हलवा",
      hi: "संक्रमण (सेप्सिस) का भारी खतरा - तुरंत उच्च केंद्र भेजें",
      en: "Prolonged rupture of membranes carrying high risk of maternal-neonatal sepsis",
      ta: "தாய் மற்றும் சேய்க்கு தீவிர கிருமித்தொற்று ஆபத்து",
    },
  },
  {
    id: "liquor_colour_green_or_brown",
    isDangerSign: true,
    category: "maternal",
    applicableSex: "female",
    onlyPregnantOrPostpartum: true,
    labels: {
      mr: "उल्बजलाचा (गर्भाशयातील पाणी) रंग हिरवा किंवा तपकिरी असणे",
      hi: "एमनियोटिक द्रव का रंग हरा या भूरा होना (मेकोनियम युक्त पानी)",
      en: "Amniotic fluid is green or brown (Meconium stained liquor)",
      ta: "பனிக்குட நீர் பச்சை அல்லது பழுப்பு நிறமாக வெளியேறுதல்",
    },
    description: {
      mr: "गर्भातील बाळाला प्राणवायू कमी पडल्याचे व धोका निर्माण झाल्याचे लक्षण",
      hi: "गर्भ में बच्चे द्वारा मल त्यागने और संकट का संकेत",
      en: "Indicates fetal distress due to meconium passage in utero",
      ta: "கருப்பையினுள் குழந்தைக்கு மூச்சுத்திணறல் அல்லது மலக்கழிவு ஏற்பட்டதன் அறிகுறி",
    },
  },
  {
    id: "prolonged_labour_pushing_gt_12h_or_gt_8h_multipara",
    isDangerSign: true,
    category: "maternal",
    applicableSex: "female",
    onlyPregnantOrPostpartum: true,
    labels: {
      mr: "लांबलेला प्रसूती काळ (पहिल्या बाळंतपणात >१२ तास किंवा नंतरच्या बाळंतपणात >८ तास)",
      hi: "लंबे समय तक प्रसव पीड़ा (पहली बार >12 घंटे या दोबारा >8 घंटे)",
      en: "Prolonged labour (Pushing >12 hours in first pregnancy or >8 hours in subsequent)",
      ta: "நீடித்த பிரசவ வலி (முதல் பிரசவத்தில் 12 மணி நேரத்திற்கும் மேல் அல்லது அடுத்த பிரசவத்தில் 8 மணி நேரத்திற்கும் மேல்)",
    },
    description: {
      mr: "अडकलेली प्रसूती - तातडीने सिझरियनची सोय असलेल्या रुग्णालयात हलवा",
      hi: "बाधित या लंबा प्रसव - आपातकालीन सिजेरियन सुविधा वाले अस्पताल भेजें",
      en: "Obstructed / prolonged labour requiring emergency C-section facility",
      ta: "தடைபட்ட பிரசவ வலி - உடனடி அறுவை சிகிச்சை வசதி தேவை",
    },
  },
  {
    id: "retained_placenta",
    isDangerSign: true,
    category: "maternal",
    applicableSex: "female",
    onlyPregnantOrPostpartum: true,
    labels: {
      mr: "बाळ जन्मल्यानंतर ३० मिनिटांत वार (प्लॅसेंटा) बाहेर न पडणे",
      hi: "शिशु जन्म के 30 मिनट बाद भी आंवल (प्लेसेंटा) बाहर न आना",
      en: "Placenta not delivered after 30 minutes of childbirth (Retained placenta)",
      ta: "பிரசவத்திற்கு பின் 30 நிமிடங்களாகியும் நச்சுக்கொடி வெளிவராமல் இருத்தல்",
    },
    description: {
      mr: "वार न पडल्यास अतिरक्तस्त्राव आणि जंतुसंसर्गाचा मोठा धोका",
      hi: "आंवल न छूटना - अत्यधिक रक्तस्राव और संक्रमण का बड़ा खतरा",
      en: "Retained placenta causing severe risk of hemorrhage and infection",
      ta: "நச்சுக்கொடி தங்கல் - அதிக இரத்தப்போக்கு மற்றும் தொற்றின் ஆபத்து",
    },
  },
  {
    id: "foul_smelling_discharge",
    isDangerSign: true,
    category: "maternal",
    applicableSex: "female",
    onlyPregnantOrPostpartum: true,
    labels: {
      mr: "गरोदरपणात किंवा बाळंतपणानंतर दुर्गंधीयुक्त योनीस्त्राव",
      hi: "गर्भावस्था या प्रसव के बाद बदबूदार योनि स्राव",
      en: "Foul-smelling vaginal discharge in pregnancy/postpartum",
      ta: "கர்ப்பம் அல்லது பிரசவத்திற்கு பின் துர்நாற்றத்துடன் கூடிய திரவப்போக்கு",
    },
    description: {
      mr: "बाळंतपणातील संसर्ग किंवा सेप्सिसचे लक्षण",
      hi: "प्रसवोत्तर संक्रमण या सेप्सिस का संकेत",
      en: "Sign of puerperal sepsis or intrauterine infection",
      ta: "பிரசவத்திற்கு பிந்தைய தொற்று அல்லது சீழ் உருவாக்கம்",
    },
  },
  {
    id: "diarrhea",
    isDangerSign: false,
    category: "digestive",
    labels: {
      mr: "जुलाब / पातळ शौचास होणे",
      hi: "दस्त / पतले दस्त होना",
      en: "Diarrhea / Loose watery stools",
      ta: "வயிற்றுப்போக்கு / பேதி",
    },
    description: {
      mr: "दिवसात ३ किंवा अधिक वेळा पातळ शौचास",
      hi: "दिन में 3 या अधिक बार पतला शौच",
      en: "Frequent loose stools",
      ta: "தொடர் வயிற்றுப்போக்கு",
    },
  },
  {
    id: "sunken_eyes",
    isDangerSign: false,
    category: "digestive",
    labels: {
      mr: "डोळे खोल जाणे (Sunken Eyes)",
      hi: "आंखें अंदर धंसना (निर्जलीकरण)",
      en: "Sunken eyes (Dehydration sign)",
      ta: "குழி விழுந்த கண்கள்",
    },
    description: {
      mr: "शरीरातील पाणी कमी झाल्याचे लक्षण",
      hi: "शरीर में पानी की कमी का संकेत",
      en: "Clinical sign of fluid volume deficit",
      ta: "நீர்ச்சத்து குறைபாட்டின் அறிகுறி",
    },
  },
  {
    id: "skin_pinch_goes_back_very_slowly",
    isDangerSign: true,
    category: "digestive",
    labels: {
      mr: "पोटाची त्वचा सोडल्यावर हळू मूळ स्थितीत जाणे",
      hi: "पेट की त्वचा चुटकी में खींचने पर बहुत धीरे जाना",
      en: "Skin pinch goes back very slowly (> 2s)",
      ta: "தோல் சுருக்கம் மீள 2 வினாடிகளுக்கு மேல் ஆகுதல்",
    },
    description: {
      mr: "अति-निर्जलीकरणाचे (Severe Dehydration) स्पष्ट लक्षण",
      hi: "गंभीर निर्जलीकरण",
      en: "Hallmark of severe acute dehydration",
      ta: "தீவிர நீர்ச்சத்து இழப்பு",
    },
  },
  {
    id: "abdominal_distension_or_swelling",
    isDangerSign: false,
    category: "digestive",
    labels: {
      mr: "पोट फुगणे किंवा सूज येणे",
      hi: "पेट में सूजन या फूलना",
      en: "Abdominal Distension or Swelling",
      ta: "வயிறு வீக்கம் அல்லது உப்புசம்",
    },
    description: {
      mr: "पोट असामान्यपणे फुगणे - वैद्यकीय तपासणी आवश्यक",
      hi: "पेट का असामान्य रूप से फूलना - स्वास्थ्य केंद्र में दिखाएं",
      en: "Progressive abdominal distension indicating ascites, obstruction, or peritonitis",
      ta: "வயிறு வழக்கத்திற்கு மாறாக பெருத்து உப்புசமாதல்",
    },
  },
  {
    id: "continuous_severe_abdominal_pain",
    isDangerSign: true,
    category: "digestive",
    labels: {
      mr: "पोटात सतत असह्य तीव्र वेदना किंवा पोट लाकडासारखे कडक होणे",
      hi: "लगातार तेज पेट दर्द या पेट का कड़ा होना",
      en: "Continuous severe abdominal pain / rigid abdomen",
      ta: "தொடர்ச்சியான கடுமையான வயிற்று வலி / வயிறு கடினமாதல்",
    },
    description: {
      mr: "तातडीच्या शस्त्रक्रियेची आवश्यकता असणारा तीव्र पोटाचा आजार",
      hi: "आपातकालीन पेट की बीमारी - तुरंत सर्जन वाले अस्पताल रेफर करें",
      en: "Sign of acute abdomen, visceral perforation, appendicitis, or obstruction",
      ta: "உடனடி அறுவை சிகிச்சை தேவைப்படக்கூடிய தீவிர வயிற்றுப் பிரச்சினை",
    },
  },
  {
    id: "stomach_pain",
    isDangerSign: false,
    category: "digestive",
    labels: {
      mr: "पोटात दुखणे किंवा कळ येणे (सौम्य ते मध्यम)",
      hi: "पेट दर्द / मरोड़ (हल्का से मध्यम)",
      en: "Stomach pain / Cramping (Mild to moderate)",
      ta: "வயிற்று வலி / தசைப்பிடிப்பு (லேசானது முதல் மிதமானது)",
    },
    description: {
      mr: "साधे पोटदुखी किंवा अपचन",
      hi: "सामान्य पेट दर्द या अपच",
      en: "Mild abdominal pain or indigestion",
      ta: "சாதாரண வயிற்று வலி அல்லது அஜீரணம்",
    },
  },
  {
    id: "unable_to_pass_stool",
    isDangerSign: true,
    category: "digestive",
    labels: {
      mr: "शौचास व गॅस पास होणे पूर्णपणे बंद होणे (आतड्यांचा अडथळा)",
      hi: "शौच या गैस पूरी तरह बंद होना (आंतों में रुकावट का संशय)",
      en: "Unable to pass stool or flatus for >48h with vomiting / distension",
      ta: "மலம் அல்லது வாயு வெளியேறாமல் அடைபடுதல்",
    },
    description: {
      mr: "आतड्यांमध्ये अडथळा निर्माण झाल्याचे लक्षण - तातडीने रुग्णालयात हलवा",
      hi: "आंत में रुकावट का गंभीर खतरा - तुरंत अस्पताल भेजें",
      en: "Sign of acute intestinal obstruction requiring urgent surgical referral",
      ta: "குடல் அடைப்புக்கான தீவிர எச்சரிக்கை",
    },
  },
  {
    id: "painful_bleeding_per_rectum",
    isDangerSign: false,
    category: "digestive",
    labels: {
      mr: "शौचाच्या वेळी रक्त पडणे व तीव्र वेदना होणे",
      hi: "शौच के साथ दर्दनाक रक्तस्राव या मल में खून आना",
      en: "Painful bleeding per rectum / Blood in stools",
      ta: "மலத்துடன் இரத்தம் வெளியேறுதல் மற்றும் கடுமையான வலி",
    },
    description: {
      mr: "आव पडणे, मूळव्याध किंवा आतड्यांमधून रक्त पडण्याचे लक्षण",
      hi: "पेचिश, बवासीर या आंतों से रक्तस्राव का संकेत",
      en: "Sign of dysentery, fissure, hemorrhoids, or lower gastrointestinal bleed",
      ta: "சீதபேதி, மூலம் அல்லது கீழ் குடல் இரத்தப்போக்கு",
    },
  },
  {
    id: "tender_swelling_behind_ear",
    isDangerSign: true,
    category: "ear",
    labels: {
      mr: "कानामागच्या भागावर सूज व तीव्र दुखणे (Mastoiditis)",
      hi: "कान के पीछे सूजन और तेज दर्द",
      en: "Tender swelling behind ear (Mastoiditis)",
      ta: "காதுக்கு பின்னால் வலி மற்றும் வீக்கம்",
    },
    description: {
      mr: "कानामागच्या हाडाचा जंतुसंसर्ग",
      hi: "कान के पीछे की हड्डी का संक्रमण",
      en: "Mastoiditis requiring prompt parenteral antibiotics",
      ta: "காது எலும்பு தீவிர தொற்று",
    },
  },
  {
    id: "ear_pain",
    isDangerSign: false,
    category: "ear",
    labels: {
      mr: "कान दुखणे",
      hi: "कान में दर्द",
      en: "Ear pain",
      ta: "காது வலி",
    },
    description: {
      mr: "कानात दुखणे किंवा ठसठस",
      hi: "कान के भीतर दर्द",
      en: "Otalgia / Ear ache",
      ta: "காதில் தொடர் வலி",
    },
  },
  {
    id: "pus_draining_less_than_14_days",
    isDangerSign: false,
    category: "ear",
    labels: {
      mr: "कानातून १४ दिवसांपेक्षा कमी काळापासून पू वाहणे",
      hi: "कान से 14 दिन से कम समय से मवाद बहना",
      en: "Pus draining from ear for less than 14 days",
      ta: "14 நாட்களுக்கும் குறைவாக காதில் சீழ் வடிதல்",
    },
    description: {
      mr: "कानाचा तीव्र संसर्ग - औषधोपचार आणि कान कोरडा ठेवणे आवश्यक",
      hi: "तीव्र कान संक्रमण - एंटीबायोटिक और कान सूखा रखने की सलाह दें",
      en: "Acute otitis media with perforation - requires oral amoxicillin and dry ear wicking",
      ta: "காதில் தீவிர சீழ் தொற்று - முறையான மருந்துகள் தேவை",
    },
  },
  {
    id: "pus_draining_14_days_or_more",
    isDangerSign: false,
    category: "ear",
    labels: {
      mr: "कानातून १४ दिवस किंवा अधिक काळापासून सतत पू वाहणे",
      hi: "कान से 14 दिन या अधिक समय से लगातार मवाद बहना",
      en: "Pus draining from ear for 14 days or more (Chronic ear infection)",
      ta: "14 நாட்கள் அல்லது அதற்கு மேலாக காதில் தொடர்ந்து சீழ் வடிதல்",
    },
    description: {
      mr: "कानाचा जुनाट संसर्ग - कान-नाक-घसा तज्ज्ञांना दाखवा",
      hi: "पुराना कान का संक्रमण - ईएनटी डॉक्टर को दिखाएं",
      en: "Chronic suppurative otitis media (CSOM) - requires ENT specialist referral",
      ta: "நீண்ட கால காது சீழ் தொற்று - காது மூக்கு தொண்டை நிபுணர் பரிசோதனை தேவை",
    },
  },
];
